CCpfcAsyncConnection = '{456E0110-2031-3907-AFE5-9201C97A915E}'
CCpfcModelDescriptor = '{74D4E90E-031B-3734-8CE1-36D5730A6728}'
CCpfcRetrieveModelOptions = '{2264B49E-C652-384F-AB53-71B57DA275BE}'
Cstringseq = '{CED94891-3E3C-33AC-978A-F2A50C45BCCD}'

class constants:
	EpfcARG_V_ASCII_STRING        =3          # from enum EpfcArgValueType
	EpfcARG_V_BOOLEAN             =2          # from enum EpfcArgValueType
	EpfcARG_V_DOUBLE              =1          # from enum EpfcArgValueType
	EpfcARG_V_INTEGER             =0          # from enum EpfcArgValueType
	EpfcARG_V_POINTER             =7          # from enum EpfcArgValueType
	EpfcARG_V_SELECTION           =5          # from enum EpfcArgValueType
	EpfcARG_V_STRING              =4          # from enum EpfcArgValueType
	EpfcARG_V_TRANSFORM           =6          # from enum EpfcArgValueType
	EpfcARG_V_WSTRING             =8          # from enum EpfcArgValueType
	EpfcArgValueType_nil          =9          # from enum EpfcArgValueType
	EpfcAssemblyConfiguration_nil =4          # from enum EpfcAssemblyConfiguration
	EpfcEXPORT_ASM_ASSEMBLY_PARTS =3          # from enum EpfcAssemblyConfiguration
	EpfcEXPORT_ASM_FLAT_FILE      =0          # from enum EpfcAssemblyConfiguration
	EpfcEXPORT_ASM_MULTI_FILES    =2          # from enum EpfcAssemblyConfiguration
	EpfcEXPORT_ASM_SINGLE_FILE    =1          # from enum EpfcAssemblyConfiguration
	EpfcATTACH_FREE               =0          # from enum EpfcAttachmentType
	EpfcATTACH_OFFSET             =3          # from enum EpfcAttachmentType
	EpfcATTACH_PARAMETRIC         =1          # from enum EpfcAttachmentType
	EpfcATTACH_TYPE_UNSUPPORTED   =2          # from enum EpfcAttachmentType
	EpfcAttachmentType_nil        =4          # from enum EpfcAttachmentType
	EpfcCGMExportType_nil         =2          # from enum EpfcCGMExportType
	EpfcEXPORT_CGM_CLEAR_TEXT     =0          # from enum EpfcCGMExportType
	EpfcEXPORT_CGM_MIL_SPEC       =1          # from enum EpfcCGMExportType
	EpfcCGMScaleType_nil          =2          # from enum EpfcCGMScaleType
	EpfcEXPORT_CGM_ABSTRACT       =0          # from enum EpfcCGMScaleType
	EpfcEXPORT_CGM_METRIC         =1          # from enum EpfcCGMScaleType
	EpfcCABLEDISP_CENTERLINE      =1          # from enum EpfcCableDisplayStyle
	EpfcCABLEDISP_DEFAULT         =0          # from enum EpfcCableDisplayStyle
	EpfcCABLEDISP_THICK           =2          # from enum EpfcCableDisplayStyle
	EpfcCableDisplayStyle_nil     =3          # from enum EpfcCableDisplayStyle
	EpfcCOL_JUSTIFY_CENTER        =1          # from enum EpfcColumnJustification
	EpfcCOL_JUSTIFY_LEFT          =0          # from enum EpfcColumnJustification
	EpfcCOL_JUSTIFY_RIGHT         =2          # from enum EpfcColumnJustification
	EpfcColumnJustification_nil   =3          # from enum EpfcColumnJustification
	EpfcACCESS_AVAILABLE          =0          # from enum EpfcCommandAccess
	EpfcACCESS_DISALLOW           =4          # from enum EpfcCommandAccess
	EpfcACCESS_INVISIBLE          =2          # from enum EpfcCommandAccess
	EpfcACCESS_REMOVE             =3          # from enum EpfcCommandAccess
	EpfcACCESS_UNAVAILABLE        =1          # from enum EpfcCommandAccess
	EpfcCommandAccess_nil         =5          # from enum EpfcCommandAccess
	EpfcASM_CONSTRAINT_ALIGN      =2          # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_ALIGN_ANG_OFF=15         # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_ALIGN_OFF  =3          # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_AUTO       =14         # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_CSYS       =6          # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_DEF_PLACEMENT=10         # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_EDGE_ON_SRF=9          # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_FIX        =13         # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_INSERT     =4          # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_MATE       =0          # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_MATE_ANG_OFF=16         # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_MATE_OFF   =1          # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_ORIENT     =5          # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_PNT_ON_LINE=12         # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_PNT_ON_SRF =8          # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_SUBSTITUTE =11         # from enum EpfcComponentConstraintType
	EpfcASM_CONSTRAINT_TANGENT    =7          # from enum EpfcComponentConstraintType
	EpfcComponentConstraintType_nil=17         # from enum EpfcComponentConstraintType
	EpfcCOMPONENT_CAST_ASSEM      =7          # from enum EpfcComponentType
	EpfcCOMPONENT_CAST_RESULT     =11         # from enum EpfcComponentType
	EpfcCOMPONENT_DIE_BLOCK       =8          # from enum EpfcComponentType
	EpfcCOMPONENT_DIE_COMP        =9          # from enum EpfcComponentType
	EpfcCOMPONENT_FIXTURE         =2          # from enum EpfcComponentType
	EpfcCOMPONENT_FROM_MOTION     =12         # from enum EpfcComponentType
	EpfcCOMPONENT_GEN_ASSEM       =6          # from enum EpfcComponentType
	EpfcCOMPONENT_MOLD_ASSEM      =5          # from enum EpfcComponentType
	EpfcCOMPONENT_MOLD_BASE       =3          # from enum EpfcComponentType
	EpfcCOMPONENT_MOLD_COMP       =4          # from enum EpfcComponentType
	EpfcCOMPONENT_NO_DEF_ASSUM    =13         # from enum EpfcComponentType
	EpfcCOMPONENT_REF_MODEL       =1          # from enum EpfcComponentType
	EpfcCOMPONENT_SAND_CORE       =10         # from enum EpfcComponentType
	EpfcCOMPONENT_WORKPIECE       =0          # from enum EpfcComponentType
	EpfcComponentType_nil         =14         # from enum EpfcComponentType
	EpfcCONTOUR_TRAV_EXTERNAL     =2          # from enum EpfcContourTraversal
	EpfcCONTOUR_TRAV_INTERNAL     =1          # from enum EpfcContourTraversal
	EpfcCONTOUR_TRAV_NONE         =0          # from enum EpfcContourTraversal
	EpfcContourTraversal_nil      =3          # from enum EpfcContourTraversal
	EpfcCOORD_AXIS_X              =0          # from enum EpfcCoordAxis
	EpfcCOORD_AXIS_Y              =1          # from enum EpfcCoordAxis
	EpfcCOORD_AXIS_Z              =2          # from enum EpfcCoordAxis
	EpfcCoordAxis_nil             =3          # from enum EpfcCoordAxis
	EpfcCURVE_END                 =1          # from enum EpfcCurveStartPoint
	EpfcCURVE_START               =0          # from enum EpfcCurveStartPoint
	EpfcCurveStartPoint_nil       =2          # from enum EpfcCurveStartPoint
	EpfcCURVE_ARC                 =4          # from enum EpfcCurveType
	EpfcCURVE_ARROW               =3          # from enum EpfcCurveType
	EpfcCURVE_BSPLINE             =6          # from enum EpfcCurveType
	EpfcCURVE_CIRCLE              =7          # from enum EpfcCurveType
	EpfcCURVE_COMPOSITE           =0          # from enum EpfcCurveType
	EpfcCURVE_ELLIPSE             =8          # from enum EpfcCurveType
	EpfcCURVE_LINE                =2          # from enum EpfcCurveType
	EpfcCURVE_POINT               =1          # from enum EpfcCurveType
	EpfcCURVE_POLYGON             =9          # from enum EpfcCurveType
	EpfcCURVE_SPLINE              =5          # from enum EpfcCurveType
	EpfcCURVE_TEXT                =10         # from enum EpfcCurveType
	EpfcCurveType_nil             =11         # from enum EpfcCurveType
	EpfcDTMAXIS_CENTER            =3          # from enum EpfcDatumAxisConstraintType
	EpfcDTMAXIS_NORMAL            =0          # from enum EpfcDatumAxisConstraintType
	EpfcDTMAXIS_TANGENT           =2          # from enum EpfcDatumAxisConstraintType
	EpfcDTMAXIS_THRU              =1          # from enum EpfcDatumAxisConstraintType
	EpfcDatumAxisConstraintType_nil=4          # from enum EpfcDatumAxisConstraintType
	EpfcDTMCSYS_DIM_ALIGN         =1          # from enum EpfcDatumCsysDimConstraintType
	EpfcDTMCSYS_DIM_OFFSET        =0          # from enum EpfcDatumCsysDimConstraintType
	EpfcDatumCsysDimConstraintType_nil=2          # from enum EpfcDatumCsysDimConstraintType
	EpfcDTMCSYS_OFFSET_CARTESIAN  =0          # from enum EpfcDatumCsysOffsetType
	EpfcDTMCSYS_OFFSET_CYLINDRICAL=1          # from enum EpfcDatumCsysOffsetType
	EpfcDTMCSYS_OFFSET_SPHERICAL  =2          # from enum EpfcDatumCsysOffsetType
	EpfcDatumCsysOffsetType_nil   =3          # from enum EpfcDatumCsysOffsetType
	EpfcDTMCSYS_ONSURF_DIAMETER   =2          # from enum EpfcDatumCsysOnSurfaceType
	EpfcDTMCSYS_ONSURF_LINEAR     =0          # from enum EpfcDatumCsysOnSurfaceType
	EpfcDTMCSYS_ONSURF_RADIAL     =1          # from enum EpfcDatumCsysOnSurfaceType
	EpfcDatumCsysOnSurfaceType_nil=3          # from enum EpfcDatumCsysOnSurfaceType
	EpfcDTMCSYS_ORIENT_BY_SEL_CSYS_AXES=1          # from enum EpfcDatumCsysOrientByMethod
	EpfcDTMCSYS_ORIENT_BY_SEL_REFS=0          # from enum EpfcDatumCsysOrientByMethod
	EpfcDatumCsysOrientByMethod_nil=2          # from enum EpfcDatumCsysOrientByMethod
	EpfcDTMCSYS_MOVE_PHI          =7          # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDTMCSYS_MOVE_RAD          =6          # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDTMCSYS_MOVE_ROT_X        =3          # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDTMCSYS_MOVE_ROT_Y        =4          # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDTMCSYS_MOVE_ROT_Z        =5          # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDTMCSYS_MOVE_THETA        =9          # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDTMCSYS_MOVE_TRAN_X       =0          # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDTMCSYS_MOVE_TRAN_Y       =1          # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDTMCSYS_MOVE_TRAN_Z       =2          # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDTMCSYS_MOVE_ZI           =8          # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDatumCsysOrientMoveConstraintType_nil=10         # from enum EpfcDatumCsysOrientMoveConstraintType
	EpfcDTMPLN_ANG                =4          # from enum EpfcDatumPlaneConstraintType
	EpfcDTMPLN_DEF_X              =7          # from enum EpfcDatumPlaneConstraintType
	EpfcDTMPLN_DEF_Y              =8          # from enum EpfcDatumPlaneConstraintType
	EpfcDTMPLN_DEF_Z              =9          # from enum EpfcDatumPlaneConstraintType
	EpfcDTMPLN_NORM               =1          # from enum EpfcDatumPlaneConstraintType
	EpfcDTMPLN_OFFS               =3          # from enum EpfcDatumPlaneConstraintType
	EpfcDTMPLN_PRL                =2          # from enum EpfcDatumPlaneConstraintType
	EpfcDTMPLN_SEC                =6          # from enum EpfcDatumPlaneConstraintType
	EpfcDTMPLN_TANG               =5          # from enum EpfcDatumPlaneConstraintType
	EpfcDTMPLN_THRU               =0          # from enum EpfcDatumPlaneConstraintType
	EpfcDatumPlaneConstraintType_nil=10         # from enum EpfcDatumPlaneConstraintType
	EpfcDTMPNT_ALONG_X            =9          # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_ALONG_Y            =10         # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_ALONG_Z            =11         # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_CARTESIAN          =12         # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_CENTER             =2          # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_CYLINDRICAL        =13         # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_LENGTH             =5          # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_LENGTH_END         =6          # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_NORMAL             =3          # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_OFFSET             =1          # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_ON                 =0          # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_PARALLEL           =4          # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_RATIO              =7          # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_RATIO_END          =8          # from enum EpfcDatumPointConstraintType
	EpfcDTMPNT_SPHERICAL          =14         # from enum EpfcDatumPointConstraintType
	EpfcDatumPointConstraintType_nil=15         # from enum EpfcDatumPointConstraintType
	EpfcDATUM_SIDE_NONE           =0          # from enum EpfcDatumSide
	EpfcDATUM_SIDE_RED            =1          # from enum EpfcDatumSide
	EpfcDATUM_SIDE_YELLOW         =2          # from enum EpfcDatumSide
	EpfcDatumSide_nil             =3          # from enum EpfcDatumSide
	EpfcDETAIL_SYMBOL_GROUP_ALL   =1          # from enum EpfcDetailSymbolGroupOption
	EpfcDETAIL_SYMBOL_GROUP_CUSTOM=3          # from enum EpfcDetailSymbolGroupOption
	EpfcDETAIL_SYMBOL_GROUP_INTERACTIVE=0          # from enum EpfcDetailSymbolGroupOption
	EpfcDETAIL_SYMBOL_GROUP_NONE  =2          # from enum EpfcDetailSymbolGroupOption
	EpfcDetailSymbolGroupOption_nil=4          # from enum EpfcDetailSymbolGroupOption
	EpfcDETAIL_DRAFT_GROUP        =4          # from enum EpfcDetailType
	EpfcDETAIL_ENTITY             =0          # from enum EpfcDetailType
	EpfcDETAIL_NOTE               =1          # from enum EpfcDetailType
	EpfcDETAIL_OLE_OBJECT         =5          # from enum EpfcDetailType
	EpfcDETAIL_SYM_DEFINITION     =2          # from enum EpfcDetailType
	EpfcDETAIL_SYM_INSTANCE       =3          # from enum EpfcDetailType
	EpfcDetailType_nil            =6          # from enum EpfcDetailType
	EpfcDIM_DISPLAY_NUMERIC       =0          # from enum EpfcDimDisplayMode
	EpfcDIM_DISPLAY_SYMBOLIC      =1          # from enum EpfcDimDisplayMode
	EpfcDimDisplayMode_nil        =2          # from enum EpfcDimDisplayMode
	EpfcDIMTOL_ISODIN             =4          # from enum EpfcDimToleranceType
	EpfcDIMTOL_LIMITS             =0          # from enum EpfcDimToleranceType
	EpfcDIMTOL_PLUS_MINUS         =1          # from enum EpfcDimToleranceType
	EpfcDIMTOL_SYMMETRIC          =2          # from enum EpfcDimToleranceType
	EpfcDIMTOL_SYMMETRIC_SUPERSCRIPT=3          # from enum EpfcDimToleranceType
	EpfcDimToleranceType_nil      =5          # from enum EpfcDimToleranceType
	EpfcDIMLINAOCTANGENT_LEFT0    =0          # from enum EpfcDimensionLinAOCTangentType
	EpfcDIMLINAOCTANGENT_LEFT1    =2          # from enum EpfcDimensionLinAOCTangentType
	EpfcDIMLINAOCTANGENT_RIGHT0   =1          # from enum EpfcDimensionLinAOCTangentType
	EpfcDIMLINAOCTANGENT_RIGHT1   =3          # from enum EpfcDimensionLinAOCTangentType
	EpfcDimensionLinAOCTangentType_nil=4          # from enum EpfcDimensionLinAOCTangentType
	EpfcDIMPOINT_CENTER           =2          # from enum EpfcDimensionPointType
	EpfcDIMPOINT_END1             =0          # from enum EpfcDimensionPointType
	EpfcDIMPOINT_END2             =1          # from enum EpfcDimensionPointType
	EpfcDIMPOINT_MIDPOINT         =4          # from enum EpfcDimensionPointType
	EpfcDIMPOINT_NONE             =3          # from enum EpfcDimensionPointType
	EpfcDimensionPointType_nil    =5          # from enum EpfcDimensionPointType
	EpfcDIMSENSE_ANGLE            =5          # from enum EpfcDimensionSenseType
	EpfcDIMSENSE_LINEAR_TO_ARC_OR_CIRCLE_TANGENT=4          # from enum EpfcDimensionSenseType
	EpfcDIMSENSE_NONE             =0          # from enum EpfcDimensionSenseType
	EpfcDIMSENSE_POINT            =1          # from enum EpfcDimensionSenseType
	EpfcDIMSENSE_POINT_TO_ANGLE   =6          # from enum EpfcDimensionSenseType
	EpfcDIMSENSE_SPLINE_PT        =2          # from enum EpfcDimensionSenseType
	EpfcDIMSENSE_TANGENT_INDEX    =3          # from enum EpfcDimensionSenseType
	EpfcDimensionSenseType_nil    =7          # from enum EpfcDimensionSenseType
	EpfcDIM_ANGULAR               =3          # from enum EpfcDimensionType
	EpfcDIM_DIAMETER              =2          # from enum EpfcDimensionType
	EpfcDIM_LINEAR                =0          # from enum EpfcDimensionType
	EpfcDIM_RADIAL                =1          # from enum EpfcDimensionType
	EpfcDimensionType_nil         =4          # from enum EpfcDimensionType
	EpfcDisplayStatus_nil         =4          # from enum EpfcDisplayStatus
	EpfcLAYER_BLANK               =2          # from enum EpfcDisplayStatus
	EpfcLAYER_DISPLAY             =1          # from enum EpfcDisplayStatus
	EpfcLAYER_HIDDEN              =3          # from enum EpfcDisplayStatus
	EpfcLAYER_NORMAL              =0          # from enum EpfcDisplayStatus
	EpfcDISPSTYLE_DEFAULT         =0          # from enum EpfcDisplayStyle
	EpfcDISPSTYLE_FOLLOW_ENVIRONMENT=5          # from enum EpfcDisplayStyle
	EpfcDISPSTYLE_HIDDEN_LINE     =2          # from enum EpfcDisplayStyle
	EpfcDISPSTYLE_NO_HIDDEN       =3          # from enum EpfcDisplayStyle
	EpfcDISPSTYLE_SHADED          =4          # from enum EpfcDisplayStyle
	EpfcDISPSTYLE_WIREFRAME       =1          # from enum EpfcDisplayStyle
	EpfcDisplayStyle_nil          =6          # from enum EpfcDisplayStyle
	EpfcDotsPerInch_nil           =6          # from enum EpfcDotsPerInch
	EpfcRASTERDPI_100             =0          # from enum EpfcDotsPerInch
	EpfcRASTERDPI_200             =1          # from enum EpfcDotsPerInch
	EpfcRASTERDPI_300             =2          # from enum EpfcDotsPerInch
	EpfcRASTERDPI_400             =3          # from enum EpfcDotsPerInch
	EpfcRASTERDPI_500             =4          # from enum EpfcDotsPerInch
	EpfcRASTERDPI_600             =5          # from enum EpfcDotsPerInch
	EpfcDWGCREATE_ERR_CANT_GET_PROJ_PARENT=11         # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_EXPLODE_DOESNT_EXIST=2          # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_FIRST_REGION_USED=6          # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_MODEL_NOT_EXPLODABLE=3          # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_NOT_PROCESS_ASSEM=7          # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_NO_PARENT_VIEW_FOR_PROJ=10         # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_NO_RPT_REGIONS=5          # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_NO_STEP_NUM =8          # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_SAVED_VIEW_DOESNT_EXIST=0          # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_SEC_NOT_PARALLEL=12         # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_SEC_NOT_PERP=4          # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_SIMP_REP_DOESNT_EXIST=13         # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_TEMPLATE_USED=9          # from enum EpfcDrawingCreateErrorType
	EpfcDWGCREATE_ERR_X_SEC_DOESNT_EXIST=1          # from enum EpfcDrawingCreateErrorType
	EpfcDWGCRTERR_COMB_STATE_DOESNT_EXIST=14         # from enum EpfcDrawingCreateErrorType
	EpfcDWGCRTERR_NOT_ALL_BALLOONS_CLEANED_WRN=16         # from enum EpfcDrawingCreateErrorType
	EpfcDWGCRTERR_TOOL_DOESNT_EXIST=15         # from enum EpfcDrawingCreateErrorType
	EpfcDrawingCreateErrorType_nil=17         # from enum EpfcDrawingCreateErrorType
	EpfcDRAWINGCREATE_DISPLAY_DRAWING=0          # from enum EpfcDrawingCreateOption
	EpfcDRAWINGCREATE_PROMPT_UNKNOWN_PARAMS=3          # from enum EpfcDrawingCreateOption
	EpfcDRAWINGCREATE_SHOW_ERROR_DIALOG=1          # from enum EpfcDrawingCreateOption
	EpfcDRAWINGCREATE_WRITE_ERROR_FILE=2          # from enum EpfcDrawingCreateOption
	EpfcDrawingCreateOption_nil   =4          # from enum EpfcDrawingCreateOption
	EpfcEXPORT_ALL                =2          # from enum EpfcExport2DSheetOption
	EpfcEXPORT_CURRENT_TO_MODEL_SPACE=0          # from enum EpfcExport2DSheetOption
	EpfcEXPORT_CURRENT_TO_PAPER_SPACE=1          # from enum EpfcExport2DSheetOption
	EpfcEXPORT_SELECTED           =3          # from enum EpfcExport2DSheetOption
	EpfcExport2DSheetOption_nil   =4          # from enum EpfcExport2DSheetOption
	EpfcEXPORT_ACIS               =26         # from enum EpfcExportType
	EpfcEXPORT_BOM                =8          # from enum EpfcExportType
	EpfcEXPORT_CABLE_PARAMS       =21         # from enum EpfcExportType
	EpfcEXPORT_CADDS              =28         # from enum EpfcExportType
	EpfcEXPORT_CATIAFACETS        =22         # from enum EpfcExportType
	EpfcEXPORT_CATIA_CGR          =38         # from enum EpfcExportType
	EpfcEXPORT_CATIA_MODEL        =25         # from enum EpfcExportType
	EpfcEXPORT_CATIA_PART         =36         # from enum EpfcExportType
	EpfcEXPORT_CATIA_PRODUCT      =37         # from enum EpfcExportType
	EpfcEXPORT_CATIA_SESSION      =27         # from enum EpfcExportType
	EpfcEXPORT_CGM                =17         # from enum EpfcExportType
	EpfcEXPORT_CONNECTOR_PARAMS   =20         # from enum EpfcExportType
	EpfcEXPORT_DWG_SETUP          =9          # from enum EpfcExportType
	EpfcEXPORT_DXF                =4          # from enum EpfcExportType
	EpfcEXPORT_FEAT_INFO          =10         # from enum EpfcExportType
	EpfcEXPORT_FIAT               =19         # from enum EpfcExportType
	EpfcEXPORT_IGES               =3          # from enum EpfcExportType
	EpfcEXPORT_IGES_3D            =14         # from enum EpfcExportType
	EpfcEXPORT_INTF_DWG           =42         # from enum EpfcExportType
	EpfcEXPORT_INTF_DXF           =41         # from enum EpfcExportType
	EpfcEXPORT_INVENTOR           =18         # from enum EpfcExportType
	EpfcEXPORT_JT                 =34         # from enum EpfcExportType
	EpfcEXPORT_MATERIAL           =13         # from enum EpfcExportType
	EpfcEXPORT_MEDUSA             =30         # from enum EpfcExportType
	EpfcEXPORT_MFG_FEAT_CL        =12         # from enum EpfcExportType
	EpfcEXPORT_MFG_OPER_CL        =11         # from enum EpfcExportType
	EpfcEXPORT_MODEL_INFO         =1          # from enum EpfcExportType
	EpfcEXPORT_NEUTRAL            =31         # from enum EpfcExportType
	EpfcEXPORT_PARASOLID          =39         # from enum EpfcExportType
	EpfcEXPORT_PDF                =33         # from enum EpfcExportType
	EpfcEXPORT_PLOT               =23         # from enum EpfcExportType
	EpfcEXPORT_PRINT              =40         # from enum EpfcExportType
	EpfcEXPORT_PRODUCTVIEW        =32         # from enum EpfcExportType
	EpfcEXPORT_PROGRAM            =2          # from enum EpfcExportType
	EpfcEXPORT_RELATION           =0          # from enum EpfcExportType
	EpfcEXPORT_RENDER             =5          # from enum EpfcExportType
	EpfcEXPORT_STEP               =15         # from enum EpfcExportType
	EpfcEXPORT_STEP_2D            =29         # from enum EpfcExportType
	EpfcEXPORT_STL_ASCII          =6          # from enum EpfcExportType
	EpfcEXPORT_STL_BINARY         =7          # from enum EpfcExportType
	EpfcEXPORT_UG                 =35         # from enum EpfcExportType
	EpfcEXPORT_VDA                =16         # from enum EpfcExportType
	EpfcEXPORT_VRML               =24         # from enum EpfcExportType
	EpfcExportType_nil            =43         # from enum EpfcExportType
	EpfcEXTDATA_DOUBLE            =1          # from enum EpfcExternalDataType
	EpfcEXTDATA_INTEGER           =0          # from enum EpfcExternalDataType
	EpfcEXTDATA_STRING            =2          # from enum EpfcExternalDataType
	EpfcExternalDataType_nil      =3          # from enum EpfcExternalDataType
	EpfcFACET_ANGLE_CONTROL_DEFAULT=4          # from enum EpfcFacetControlFlag
	EpfcFACET_CHORD_HEIGHT_ADJUST =1          # from enum EpfcFacetControlFlag
	EpfcFACET_CHORD_HEIGHT_DEFAULT=3          # from enum EpfcFacetControlFlag
	EpfcFACET_FORCE_INTO_RANGE    =7          # from enum EpfcFacetControlFlag
	EpfcFACET_STEP_SIZE_ADJUST    =0          # from enum EpfcFacetControlFlag
	EpfcFACET_STEP_SIZE_DEFAULT   =5          # from enum EpfcFacetControlFlag
	EpfcFACET_STEP_SIZE_OFF       =6          # from enum EpfcFacetControlFlag
	EpfcFACET_USE_CONFIG          =2          # from enum EpfcFacetControlFlag
	EpfcFacetControlFlag_nil      =8          # from enum EpfcFacetControlFlag
	EpfcFAM_ANNOT_ELEM_PARAM      =24         # from enum EpfcFamilyColumnType
	EpfcFAM_ASMCOMP               =4          # from enum EpfcFamilyColumnType
	EpfcFAM_ASMCOMP_MODEL         =6          # from enum EpfcFamilyColumnType
	EpfcFAM_COMP_CURVE_PARAM      =22         # from enum EpfcFamilyColumnType
	EpfcFAM_CONNECTION_PARAM      =25         # from enum EpfcFamilyColumnType
	EpfcFAM_CURVE_PARAM           =21         # from enum EpfcFamilyColumnType
	EpfcFAM_DIMENSION             =1          # from enum EpfcFamilyColumnType
	EpfcFAM_EDGE_PARAM            =19         # from enum EpfcFamilyColumnType
	EpfcFAM_EXTERNAL_REFERENCE    =12         # from enum EpfcFamilyColumnType
	EpfcFAM_FEATURE               =3          # from enum EpfcFamilyColumnType
	EpfcFAM_FEATURE_PARAM         =18         # from enum EpfcFamilyColumnType
	EpfcFAM_GTOL                  =7          # from enum EpfcFamilyColumnType
	EpfcFAM_INH_PART_REF          =16         # from enum EpfcFamilyColumnType
	EpfcFAM_IPAR_NOTE             =2          # from enum EpfcFamilyColumnType
	EpfcFAM_MASS_PROPS_SOURCE     =15         # from enum EpfcFamilyColumnType
	EpfcFAM_MASS_PROPS_USER_PARAM =14         # from enum EpfcFamilyColumnType
	EpfcFAM_MERGE_PART_REF        =13         # from enum EpfcFamilyColumnType
	EpfcFAM_QUILT_PARAM           =23         # from enum EpfcFamilyColumnType
	EpfcFAM_SIM_OBJ               =17         # from enum EpfcFamilyColumnType
	EpfcFAM_SURFACE_PARAM         =20         # from enum EpfcFamilyColumnType
	EpfcFAM_SYSTEM_PARAM          =11         # from enum EpfcFamilyColumnType
	EpfcFAM_TOL_MINUS             =9          # from enum EpfcFamilyColumnType
	EpfcFAM_TOL_PLUS              =8          # from enum EpfcFamilyColumnType
	EpfcFAM_TOL_PLUSMINUS         =10         # from enum EpfcFamilyColumnType
	EpfcFAM_UDF                   =5          # from enum EpfcFamilyColumnType
	EpfcFAM_USER_PARAM            =0          # from enum EpfcFamilyColumnType
	EpfcFamilyColumnType_nil      =26         # from enum EpfcFamilyColumnType
	EpfcFAMINST_FAILED_VERIFIED   =1          # from enum EpfcFaminstanceVerifyStatus
	EpfcFAMINST_NOT_VERIFIED      =2          # from enum EpfcFaminstanceVerifyStatus
	EpfcFAMINST_SUCCESS_VERIFIED  =0          # from enum EpfcFaminstanceVerifyStatus
	EpfcFaminstanceVerifyStatus_nil=3          # from enum EpfcFaminstanceVerifyStatus
	EpfcFEATCOPY_MIRROR           =2          # from enum EpfcFeatureCopyType
	EpfcFEATCOPY_MOVE             =3          # from enum EpfcFeatureCopyType
	EpfcFEATCOPY_NEWREFS          =0          # from enum EpfcFeatureCopyType
	EpfcFEATCOPY_SAMEREFS         =1          # from enum EpfcFeatureCopyType
	EpfcFeatureCopyType_nil       =4          # from enum EpfcFeatureCopyType
	EpfcFEAT_ACTIVE               =0          # from enum EpfcFeatureStatus
	EpfcFEAT_FAMILY_TABLE_SUPPRESSED=2          # from enum EpfcFeatureStatus
	EpfcFEAT_INACTIVE             =1          # from enum EpfcFeatureStatus
	EpfcFEAT_PROGRAM_SUPPRESSED   =4          # from enum EpfcFeatureStatus
	EpfcFEAT_SIMP_REP_SUPPRESSED  =3          # from enum EpfcFeatureStatus
	EpfcFEAT_SUPPRESSED           =5          # from enum EpfcFeatureStatus
	EpfcFEAT_UNREGENERATED        =6          # from enum EpfcFeatureStatus
	EpfcFeatureStatus_nil         =7          # from enum EpfcFeatureStatus
	EpfcFEATTYPE_ANALYSIS         =168        # from enum EpfcFeatureType
	EpfcFEATTYPE_ANALYT_GEOM      =261        # from enum EpfcFeatureType
	EpfcFEATTYPE_ANNOTATION       =235        # from enum EpfcFeatureType
	EpfcFEATTYPE_AREA_NIBBLE      =70         # from enum EpfcFeatureType
	EpfcFEATTYPE_ARTWORK          =246        # from enum EpfcFeatureType
	EpfcFEATTYPE_ASSEMBLY_CUT     =37         # from enum EpfcFeatureType
	EpfcFEATTYPE_ASSEMBLY_CUT_COPY=145        # from enum EpfcFeatureType
	EpfcFEATTYPE_ASSY_MERGE       =209        # from enum EpfcFeatureType
	EpfcFEATTYPE_ASSY_WELD_NOTCH  =215        # from enum EpfcFeatureType
	EpfcFEATTYPE_ATTACH           =81         # from enum EpfcFeatureType
	EpfcFEATTYPE_ATTACH_VOLUME    =130        # from enum EpfcFeatureType
	EpfcFEATTYPE_AUTO_ROUND       =243        # from enum EpfcFeatureType
	EpfcFEATTYPE_AUXILIARY        =112        # from enum EpfcFeatureType
	EpfcFEATTYPE_BEAM_SECTION     =151        # from enum EpfcFeatureType
	EpfcFEATTYPE_BEND             =42         # from enum EpfcFeatureType
	EpfcFEATTYPE_BEND_BACK        =47         # from enum EpfcFeatureType
	EpfcFEATTYPE_BLD_OPERATION    =131        # from enum EpfcFeatureType
	EpfcFEATTYPE_BULK_OBJECT      =116        # from enum EpfcFeatureType
	EpfcFEATTYPE_CABLE            =67         # from enum EpfcFeatureType
	EpfcFEATTYPE_CABLE_COSMETIC   =87         # from enum EpfcFeatureType
	EpfcFEATTYPE_CABLE_LOCATION   =65         # from enum EpfcFeatureType
	EpfcFEATTYPE_CABLE_SEGMENT    =66         # from enum EpfcFeatureType
	EpfcFEATTYPE_CAV_DEVIATION    =160        # from enum EpfcFeatureType
	EpfcFEATTYPE_CAV_FIT          =159        # from enum EpfcFeatureType
	EpfcFEATTYPE_CAV_SCAN_SET     =158        # from enum EpfcFeatureType
	EpfcFEATTYPE_CE_GEOM          =260        # from enum EpfcFeatureType
	EpfcFEATTYPE_CHAMFER          =4          # from enum EpfcFeatureType
	EpfcFEATTYPE_CHANNEL          =69         # from enum EpfcFeatureType
	EpfcFEATTYPE_CMMCONSTR        =156        # from enum EpfcFeatureType
	EpfcFEATTYPE_CMMMEASURE_STEP  =155        # from enum EpfcFeatureType
	EpfcFEATTYPE_CMMVERIFY        =157        # from enum EpfcFeatureType
	EpfcFEATTYPE_COMPONENT        =89         # from enum EpfcFeatureType
	EpfcFEATTYPE_COMP_INTERFACE   =211        # from enum EpfcFeatureType
	EpfcFEATTYPE_CONTACT3D        =248        # from enum EpfcFeatureType
	EpfcFEATTYPE_CONT_MAP         =93         # from enum EpfcFeatureType
	EpfcFEATTYPE_COORD_SYS        =68         # from enum EpfcFeatureType
	EpfcFEATTYPE_CORE             =73         # from enum EpfcFeatureType
	EpfcFEATTYPE_CORNER_CHAMFER   =20         # from enum EpfcFeatureType
	EpfcFEATTYPE_COSMETIC         =23         # from enum EpfcFeatureType
	EpfcFEATTYPE_CROSS_SECTION    =82         # from enum EpfcFeatureType
	EpfcFEATTYPE_CURVE            =39         # from enum EpfcFeatureType
	EpfcFEATTYPE_CUSTOMIZE        =99         # from enum EpfcFeatureType
	EpfcFEATTYPE_CUT              =6          # from enum EpfcFeatureType
	EpfcFEATTYPE_CUT_MOTION       =98         # from enum EpfcFeatureType
	EpfcFEATTYPE_DAMPER           =241        # from enum EpfcFeatureType
	EpfcFEATTYPE_DATUM_AXIS       =16         # from enum EpfcFeatureType
	EpfcFEATTYPE_DATUM_PLANE      =13         # from enum EpfcFeatureType
	EpfcFEATTYPE_DATUM_POINT      =21         # from enum EpfcFeatureType
	EpfcFEATTYPE_DATUM_QUILT      =36         # from enum EpfcFeatureType
	EpfcFEATTYPE_DATUM_SURFACE    =32         # from enum EpfcFeatureType
	EpfcFEATTYPE_DECLARE          =123        # from enum EpfcFeatureType
	EpfcFEATTYPE_DEFORM_AREA      =146        # from enum EpfcFeatureType
	EpfcFEATTYPE_DESIGNATED_AREA  =244        # from enum EpfcFeatureType
	EpfcFEATTYPE_DOME             =12         # from enum EpfcFeatureType
	EpfcFEATTYPE_DOME2            =19         # from enum EpfcFeatureType
	EpfcFEATTYPE_DRAFT            =17         # from enum EpfcFeatureType
	EpfcFEATTYPE_DRAFT_LINE       =127        # from enum EpfcFeatureType
	EpfcFEATTYPE_DRILL            =30         # from enum EpfcFeatureType
	EpfcFEATTYPE_DRILL_GROUP      =85         # from enum EpfcFeatureType
	EpfcFEATTYPE_DRVD             =182        # from enum EpfcFeatureType
	EpfcFEATTYPE_DRV_TOOL_CURVE   =102        # from enum EpfcFeatureType
	EpfcFEATTYPE_DRV_TOOL_EDGE    =101        # from enum EpfcFeatureType
	EpfcFEATTYPE_DRV_TOOL_PROFILE =165        # from enum EpfcFeatureType
	EpfcFEATTYPE_DRV_TOOL_SKETCH  =100        # from enum EpfcFeatureType
	EpfcFEATTYPE_DRV_TOOL_SURF    =103        # from enum EpfcFeatureType
	EpfcFEATTYPE_DRV_TOOL_TURN    =186        # from enum EpfcFeatureType
	EpfcFEATTYPE_DRV_TOOL_TWO_CNTR=120        # from enum EpfcFeatureType
	EpfcFEATTYPE_DS_OPTIMIZE      =210        # from enum EpfcFeatureType
	EpfcFEATTYPE_EAR              =11         # from enum EpfcFeatureType
	EpfcFEATTYPE_EDGE_BEND        =164        # from enum EpfcFeatureType
	EpfcFEATTYPE_ETCH             =24         # from enum EpfcFeatureType
	EpfcFEATTYPE_EXPLODE_LINE     =166        # from enum EpfcFeatureType
	EpfcFEATTYPE_EXP_RATIO        =94         # from enum EpfcFeatureType
	EpfcFEATTYPE_EXTEND           =78         # from enum EpfcFeatureType
	EpfcFEATTYPE_EXTRACT          =74         # from enum EpfcFeatureType
	EpfcFEATTYPE_FIRST            =0          # from enum EpfcFeatureType
	EpfcFEATTYPE_FIXTURE_SETUP    =91         # from enum EpfcFeatureType
	EpfcFEATTYPE_FLANGE           =9          # from enum EpfcFeatureType
	EpfcFEATTYPE_FLATQLT          =185        # from enum EpfcFeatureType
	EpfcFEATTYPE_FLATTEN          =55         # from enum EpfcFeatureType
	EpfcFEATTYPE_FLAT_PAT         =92         # from enum EpfcFeatureType
	EpfcFEATTYPE_FLAT_RIBBON_SEGMENT=148        # from enum EpfcFeatureType
	EpfcFEATTYPE_FLEXMOVE         =255        # from enum EpfcFeatureType
	EpfcFEATTYPE_FLEXSUBST        =258        # from enum EpfcFeatureType
	EpfcFEATTYPE_FLEX_MUTATOR     =234        # from enum EpfcFeatureType
	EpfcFEATTYPE_FLXATTACH        =257        # from enum EpfcFeatureType
	EpfcFEATTYPE_FORM             =45         # from enum EpfcFeatureType
	EpfcFEATTYPE_FREEFORM         =202        # from enum EpfcFeatureType
	EpfcFEATTYPE_FREE_FORM        =135        # from enum EpfcFeatureType
	EpfcFEATTYPE_FR_SYS           =198        # from enum EpfcFeatureType
	EpfcFEATTYPE_GENERAL_MERGE    =240        # from enum EpfcFeatureType
	EpfcFEATTYPE_GEOM_COPY        =167        # from enum EpfcFeatureType
	EpfcFEATTYPE_GLOBAL_MODEL     =229        # from enum EpfcFeatureType
	EpfcFEATTYPE_GRANITE_REMOVE_SRFS=236        # from enum EpfcFeatureType
	EpfcFEATTYPE_GRANITE_TAPER_EXTR=237        # from enum EpfcFeatureType
	EpfcFEATTYPE_GRANITE_TOOL_COMP=238        # from enum EpfcFeatureType
	EpfcFEATTYPE_GRAPH            =52         # from enum EpfcFeatureType
	EpfcFEATTYPE_GROOVE           =34         # from enum EpfcFeatureType
	EpfcFEATTYPE_GROUP_HEAD       =181        # from enum EpfcFeatureType
	EpfcFEATTYPE_HOLE             =1          # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_BEAM        =191        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_BRACKET     =196        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_COLLAR      =194        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_COMPT       =199        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_CUTOUT      =189        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_DRAW        =195        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_ENDCUT      =192        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_FOLDED_FLG  =197        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_HOLE        =188        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_MITRE       =230        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_PAD         =227        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_PLATE       =187        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_REP_TMP     =205        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_SLOTCUT     =231        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_SPLIT_BOUND =224        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_STIFFENER   =190        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_WELD_NOTCH  =217        # from enum EpfcFeatureType
	EpfcFEATTYPE_HULL_WLD_FLANGE  =193        # from enum EpfcFeatureType
	EpfcFEATTYPE_IMPORT           =22         # from enum EpfcFeatureType
	EpfcFEATTYPE_INSULATION       =206        # from enum EpfcFeatureType
	EpfcFEATTYPE_INTERNAL_UDF     =50         # from enum EpfcFeatureType
	EpfcFEATTYPE_INTERSECT        =80         # from enum EpfcFeatureType
	EpfcFEATTYPE_IPMQUILT         =179        # from enum EpfcFeatureType
	EpfcFEATTYPE_ISEGMENT         =86         # from enum EpfcFeatureType
	EpfcFEATTYPE_KERNEL           =203        # from enum EpfcFeatureType
	EpfcFEATTYPE_LINE_STOCK       =114        # from enum EpfcFeatureType
	EpfcFEATTYPE_LIP              =60         # from enum EpfcFeatureType
	EpfcFEATTYPE_LOC_PUSH         =14         # from enum EpfcFeatureType
	EpfcFEATTYPE_MANUAL_MILL      =61         # from enum EpfcFeatureType
	EpfcFEATTYPE_MATERIAL_REMOVAL =104        # from enum EpfcFeatureType
	EpfcFEATTYPE_MEASURE          =126        # from enum EpfcFeatureType
	EpfcFEATTYPE_MERGE            =25         # from enum EpfcFeatureType
	EpfcFEATTYPE_MFGGATHER        =62         # from enum EpfcFeatureType
	EpfcFEATTYPE_MFGMERGE         =90         # from enum EpfcFeatureType
	EpfcFEATTYPE_MFGREFINE        =75         # from enum EpfcFeatureType
	EpfcFEATTYPE_MFGTRIM          =63         # from enum EpfcFeatureType
	EpfcFEATTYPE_MFGUSE_VOLUME    =64         # from enum EpfcFeatureType
	EpfcFEATTYPE_MILL             =29         # from enum EpfcFeatureType
	EpfcFEATTYPE_MOD_ROUND        =259        # from enum EpfcFeatureType
	EpfcFEATTYPE_MOLD             =26         # from enum EpfcFeatureType
	EpfcFEATTYPE_MOLD_SLIDER      =226        # from enum EpfcFeatureType
	EpfcFEATTYPE_NECK             =8          # from enum EpfcFeatureType
	EpfcFEATTYPE_OFFSET           =31         # from enum EpfcFeatureType
	EpfcFEATTYPE_OLE              =212        # from enum EpfcFeatureType
	EpfcFEATTYPE_OPERATION        =96         # from enum EpfcFeatureType
	EpfcFEATTYPE_OPERATION_COMPONENT=125        # from enum EpfcFeatureType
	EpfcFEATTYPE_PATCH            =71         # from enum EpfcFeatureType
	EpfcFEATTYPE_PATTERN          =232        # from enum EpfcFeatureType
	EpfcFEATTYPE_PATTERN_HEAD     =233        # from enum EpfcFeatureType
	EpfcFEATTYPE_PIPE             =35         # from enum EpfcFeatureType
	EpfcFEATTYPE_PIPE_BRANCH      =119        # from enum EpfcFeatureType
	EpfcFEATTYPE_PIPE_EXTEND      =108        # from enum EpfcFeatureType
	EpfcFEATTYPE_PIPE_FOLLOW      =110        # from enum EpfcFeatureType
	EpfcFEATTYPE_PIPE_JOIN        =111        # from enum EpfcFeatureType
	EpfcFEATTYPE_PIPE_JOINT       =118        # from enum EpfcFeatureType
	EpfcFEATTYPE_PIPE_LINE        =113        # from enum EpfcFeatureType
	EpfcFEATTYPE_PIPE_POINT_TO_POINT=107        # from enum EpfcFeatureType
	EpfcFEATTYPE_PIPE_SET_START   =106        # from enum EpfcFeatureType
	EpfcFEATTYPE_PIPE_TRIM        =109        # from enum EpfcFeatureType
	EpfcFEATTYPE_PLASTIC_RIB      =251        # from enum EpfcFeatureType
	EpfcFEATTYPE_PLY              =72         # from enum EpfcFeatureType
	EpfcFEATTYPE_PM_BELT_CURVE    =252        # from enum EpfcFeatureType
	EpfcFEATTYPE_PM_BUSHING_LD    =256        # from enum EpfcFeatureType
	EpfcFEATTYPE_POSITION_FOLD    =149        # from enum EpfcFeatureType
	EpfcFEATTYPE_PROCESS_STEP     =163        # from enum EpfcFeatureType
	EpfcFEATTYPE_PROTRUSION       =7          # from enum EpfcFeatureType
	EpfcFEATTYPE_REFERENCE        =200        # from enum EpfcFeatureType
	EpfcFEATTYPE_REMOVE_SURFACE   =245        # from enum EpfcFeatureType
	EpfcFEATTYPE_REMOVE_SURFACES  =128        # from enum EpfcFeatureType
	EpfcFEATTYPE_REPLACE_SURFACE  =33         # from enum EpfcFeatureType
	EpfcFEATTYPE_RIB              =10         # from enum EpfcFeatureType
	EpfcFEATTYPE_RIBBON_CABLE     =129        # from enum EpfcFeatureType
	EpfcFEATTYPE_RIBBON_EXTEND    =144        # from enum EpfcFeatureType
	EpfcFEATTYPE_RIBBON_PATH      =143        # from enum EpfcFeatureType
	EpfcFEATTYPE_RIBBON_SOLID     =147        # from enum EpfcFeatureType
	EpfcFEATTYPE_RIP              =95         # from enum EpfcFeatureType
	EpfcFEATTYPE_ROUND            =3          # from enum EpfcFeatureType
	EpfcFEATTYPE_ROUTE_MANAGER    =216        # from enum EpfcFeatureType
	EpfcFEATTYPE_ROUTE_PATH       =223        # from enum EpfcFeatureType
	EpfcFEATTYPE_ROUTE_SPOOL      =228        # from enum EpfcFeatureType
	EpfcFEATTYPE_RS_GENERATOR     =249        # from enum EpfcFeatureType
	EpfcFEATTYPE_RS_TRJ_MOVE      =250        # from enum EpfcFeatureType
	EpfcFEATTYPE_SAW              =27         # from enum EpfcFeatureType
	EpfcFEATTYPE_SET              =56         # from enum EpfcFeatureType
	EpfcFEATTYPE_SHAFT            =2          # from enum EpfcFeatureType
	EpfcFEATTYPE_SHEETMETAL_CLAMP =162        # from enum EpfcFeatureType
	EpfcFEATTYPE_SHEETMETAL_CONVERSION=154        # from enum EpfcFeatureType
	EpfcFEATTYPE_SHEETMETAL_CUT   =44         # from enum EpfcFeatureType
	EpfcFEATTYPE_SHEETMETAL_OPTIMIZE=122        # from enum EpfcFeatureType
	EpfcFEATTYPE_SHEETMETAL_POPULATE=124        # from enum EpfcFeatureType
	EpfcFEATTYPE_SHEETMETAL_PUNCH_POINT=59         # from enum EpfcFeatureType
	EpfcFEATTYPE_SHEETMETAL_SHEAR =142        # from enum EpfcFeatureType
	EpfcFEATTYPE_SHEETMETAL_ZONE  =161        # from enum EpfcFeatureType
	EpfcFEATTYPE_SHELL            =18         # from enum EpfcFeatureType
	EpfcFEATTYPE_SHELL_EXP        =201        # from enum EpfcFeatureType
	EpfcFEATTYPE_SHRINKAGE        =117        # from enum EpfcFeatureType
	EpfcFEATTYPE_SHRINK_DIM       =152        # from enum EpfcFeatureType
	EpfcFEATTYPE_SILHOUETTE_TRIM  =76         # from enum EpfcFeatureType
	EpfcFEATTYPE_SLDBEND          =184        # from enum EpfcFeatureType
	EpfcFEATTYPE_SLD_PIP_INSUL    =207        # from enum EpfcFeatureType
	EpfcFEATTYPE_SLOT             =5          # from enum EpfcFeatureType
	EpfcFEATTYPE_SMMFGAPPROACH    =176        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMMFGCOSMETIC    =175        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMMFGCUT         =54         # from enum EpfcFeatureType
	EpfcFEATTYPE_SMMFGFORM        =58         # from enum EpfcFeatureType
	EpfcFEATTYPE_SMMFGMATERIAL_REMOVE=174        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMMFGOFFSET      =173        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMMFGPUNCH       =53         # from enum EpfcFeatureType
	EpfcFEATTYPE_SMMFGSHAPE       =178        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMMFGSLOT        =177        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMM_ETCH         =222        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMM_GROOVE       =221        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMM_HOLE         =219        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMM_NEST         =220        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMM_SLIT         =218        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMT_CRN_REL      =183        # from enum EpfcFeatureType
	EpfcFEATTYPE_SMT_EXTRACT      =208        # from enum EpfcFeatureType
	EpfcFEATTYPE_SOLIDIFY         =79         # from enum EpfcFeatureType
	EpfcFEATTYPE_SOLID_PIPE       =115        # from enum EpfcFeatureType
	EpfcFEATTYPE_SPINAL_BEND      =133        # from enum EpfcFeatureType
	EpfcFEATTYPE_SPLIT            =77         # from enum EpfcFeatureType
	EpfcFEATTYPE_SPLIT_SURFACE    =51         # from enum EpfcFeatureType
	EpfcFEATTYPE_SPOOL            =88         # from enum EpfcFeatureType
	EpfcFEATTYPE_SPRING           =242        # from enum EpfcFeatureType
	EpfcFEATTYPE_SPRING_BACK      =150        # from enum EpfcFeatureType
	EpfcFEATTYPE_STAMPED_AREA     =262        # from enum EpfcFeatureType
	EpfcFEATTYPE_STYLE            =239        # from enum EpfcFeatureType
	EpfcFEATTYPE_SUBDIVISION      =254        # from enum EpfcFeatureType
	EpfcFEATTYPE_SUB_HARNESS      =121        # from enum EpfcFeatureType
	EpfcFEATTYPE_SUPERQUILT       =225        # from enum EpfcFeatureType
	EpfcFEATTYPE_SURFACE_MODEL    =40         # from enum EpfcFeatureType
	EpfcFEATTYPE_TERMINATOR       =213        # from enum EpfcFeatureType
	EpfcFEATTYPE_THICKEN          =46         # from enum EpfcFeatureType
	EpfcFEATTYPE_THREAD           =153        # from enum EpfcFeatureType
	EpfcFEATTYPE_TORUS            =105        # from enum EpfcFeatureType
	EpfcFEATTYPE_TURN             =28         # from enum EpfcFeatureType
	EpfcFEATTYPE_TWIST            =134        # from enum EpfcFeatureType
	EpfcFEATTYPE_UDF              =15         # from enum EpfcFeatureType
	EpfcFEATTYPE_UDFCLAMP         =84         # from enum EpfcFeatureType
	EpfcFEATTYPE_UDFNOTCH         =48         # from enum EpfcFeatureType
	EpfcFEATTYPE_UDFPUNCH         =49         # from enum EpfcFeatureType
	EpfcFEATTYPE_UDFRMDT          =170        # from enum EpfcFeatureType
	EpfcFEATTYPE_UDFTHREAD        =38         # from enum EpfcFeatureType
	EpfcFEATTYPE_UDFWORK_REGION   =132        # from enum EpfcFeatureType
	EpfcFEATTYPE_UDFZONE          =83         # from enum EpfcFeatureType
	EpfcFEATTYPE_UNBEND           =43         # from enum EpfcFeatureType
	EpfcFEATTYPE_USER             =180        # from enum EpfcFeatureType
	EpfcFEATTYPE_VDA              =57         # from enum EpfcFeatureType
	EpfcFEATTYPE_VOL_SPLIT        =171        # from enum EpfcFeatureType
	EpfcFEATTYPE_VPDD             =253        # from enum EpfcFeatureType
	EpfcFEATTYPE_WALL             =41         # from enum EpfcFeatureType
	EpfcFEATTYPE_WATER_LINE       =169        # from enum EpfcFeatureType
	EpfcFEATTYPE_WELDING_ROD      =137        # from enum EpfcFeatureType
	EpfcFEATTYPE_WELD_COMBINE     =247        # from enum EpfcFeatureType
	EpfcFEATTYPE_WELD_EDGE_PREP   =172        # from enum EpfcFeatureType
	EpfcFEATTYPE_WELD_FILLET      =138        # from enum EpfcFeatureType
	EpfcFEATTYPE_WELD_GROOVE      =139        # from enum EpfcFeatureType
	EpfcFEATTYPE_WELD_NOTCH       =214        # from enum EpfcFeatureType
	EpfcFEATTYPE_WELD_PLUG_SLOT   =140        # from enum EpfcFeatureType
	EpfcFEATTYPE_WELD_PROCESS     =204        # from enum EpfcFeatureType
	EpfcFEATTYPE_WELD_SPOT        =141        # from enum EpfcFeatureType
	EpfcFEATTYPE_WORKCELL         =97         # from enum EpfcFeatureType
	EpfcFEATTYPE_ZONE             =136        # from enum EpfcFeatureType
	EpfcFeatureType_nil           =263        # from enum EpfcFeatureType
	EpfcFILE_LIST_ALL             =0          # from enum EpfcFileListOpt
	EpfcFILE_LIST_ALL_INST        =2          # from enum EpfcFileListOpt
	EpfcFILE_LIST_LATEST          =1          # from enum EpfcFileListOpt
	EpfcFILE_LIST_LATEST_INST     =3          # from enum EpfcFileListOpt
	EpfcFileListOpt_nil           =4          # from enum EpfcFileListOpt
	EpfcDRAW_GRAPHICS_COMPLEMENT  =1          # from enum EpfcGraphicsMode
	EpfcDRAW_GRAPHICS_NORMAL      =0          # from enum EpfcGraphicsMode
	EpfcGraphicsMode_nil          =2          # from enum EpfcGraphicsMode
	EpfcH_JUSTIFY_CENTER          =1          # from enum EpfcHorizontalJustification
	EpfcH_JUSTIFY_DEFAULT         =3          # from enum EpfcHorizontalJustification
	EpfcH_JUSTIFY_LEFT            =0          # from enum EpfcHorizontalJustification
	EpfcH_JUSTIFY_RIGHT           =2          # from enum EpfcHorizontalJustification
	EpfcHorizontalJustification_nil=4          # from enum EpfcHorizontalJustification
	EpfcIMPORT_LAYER_BLANK        =2          # from enum EpfcImportAction
	EpfcIMPORT_LAYER_DISPLAY      =0          # from enum EpfcImportAction
	EpfcIMPORT_LAYER_HIDDEN       =5          # from enum EpfcImportAction
	EpfcIMPORT_LAYER_IGNORE       =3          # from enum EpfcImportAction
	EpfcIMPORT_LAYER_NORMAL       =4          # from enum EpfcImportAction
	EpfcIMPORT_LAYER_SKIP         =1          # from enum EpfcImportAction
	EpfcImportAction_nil          =6          # from enum EpfcImportAction
	EpfcIMPORT_2D_CADAM           =14         # from enum EpfcImportType
	EpfcIMPORT_2D_DWG             =13         # from enum EpfcImportType
	EpfcIMPORT_2D_DXF             =12         # from enum EpfcImportType
	EpfcIMPORT_2D_IGES            =11         # from enum EpfcImportType
	EpfcIMPORT_2D_STEP            =10         # from enum EpfcImportType
	EpfcIMPORT_ASSEM_TREE_CFG     =8          # from enum EpfcImportType
	EpfcIMPORT_CABLE_PARAMS       =7          # from enum EpfcImportType
	EpfcIMPORT_CONFIG             =3          # from enum EpfcImportType
	EpfcIMPORT_CONNECTOR_PARAMS   =6          # from enum EpfcImportType
	EpfcIMPORT_DWG_SETUP          =4          # from enum EpfcImportType
	EpfcIMPORT_IGES_SECTION       =1          # from enum EpfcImportType
	EpfcIMPORT_PROGRAM            =2          # from enum EpfcImportType
	EpfcIMPORT_RELATION           =0          # from enum EpfcImportType
	EpfcIMPORT_SPOOL              =5          # from enum EpfcImportType
	EpfcIMPORT_WIRELIST           =9          # from enum EpfcImportType
	EpfcImportType_nil            =15         # from enum EpfcImportType
	EpfcINTF_ACIS                 =6          # from enum EpfcIntfType
	EpfcINTF_AI                   =12         # from enum EpfcIntfType
	EpfcINTF_CATIA_CGR            =17         # from enum EpfcIntfType
	EpfcINTF_CATIA_PART           =13         # from enum EpfcIntfType
	EpfcINTF_CATIA_PRODUCT        =16         # from enum EpfcIntfType
	EpfcINTF_CDRS                 =8          # from enum EpfcIntfType
	EpfcINTF_DXF                  =7          # from enum EpfcIntfType
	EpfcINTF_IBL                  =21         # from enum EpfcIntfType
	EpfcINTF_ICEM                 =5          # from enum EpfcIntfType
	EpfcINTF_IGES                 =2          # from enum EpfcIntfType
	EpfcINTF_INVENTOR_ASM         =20         # from enum EpfcIntfType
	EpfcINTF_INVENTOR_PART        =19         # from enum EpfcIntfType
	EpfcINTF_JT                   =18         # from enum EpfcIntfType
	EpfcINTF_NEUTRAL              =0          # from enum EpfcIntfType
	EpfcINTF_NEUTRAL_FILE         =1          # from enum EpfcIntfType
	EpfcINTF_PARASOLID            =11         # from enum EpfcIntfType
	EpfcINTF_PRODUCTVIEW          =15         # from enum EpfcIntfType
	EpfcINTF_PTS                  =22         # from enum EpfcIntfType
	EpfcINTF_STEP                 =3          # from enum EpfcIntfType
	EpfcINTF_STL                  =9          # from enum EpfcIntfType
	EpfcINTF_UG                   =14         # from enum EpfcIntfType
	EpfcINTF_VDA                  =4          # from enum EpfcIntfType
	EpfcINTF_VRML                 =10         # from enum EpfcIntfType
	EpfcIntfType_nil              =23         # from enum EpfcIntfType
	EpfcLENGTHUNIT_CM             =3          # from enum EpfcLengthUnitType
	EpfcLENGTHUNIT_FOOT           =1          # from enum EpfcLengthUnitType
	EpfcLENGTHUNIT_INCH           =0          # from enum EpfcLengthUnitType
	EpfcLENGTHUNIT_KM             =7          # from enum EpfcLengthUnitType
	EpfcLENGTHUNIT_M              =4          # from enum EpfcLengthUnitType
	EpfcLENGTHUNIT_MCM            =5          # from enum EpfcLengthUnitType
	EpfcLENGTHUNIT_MILE           =8          # from enum EpfcLengthUnitType
	EpfcLENGTHUNIT_MM             =2          # from enum EpfcLengthUnitType
	EpfcLENGTHUNIT_NM             =6          # from enum EpfcLengthUnitType
	EpfcLengthUnitType_nil        =9          # from enum EpfcLengthUnitType
	EpfcMASSUNIT_GRAM             =3          # from enum EpfcMassUnitType
	EpfcMASSUNIT_KILOGRAM         =4          # from enum EpfcMassUnitType
	EpfcMASSUNIT_OUNCE            =0          # from enum EpfcMassUnitType
	EpfcMASSUNIT_POUND            =1          # from enum EpfcMassUnitType
	EpfcMASSUNIT_TON              =2          # from enum EpfcMassUnitType
	EpfcMASSUNIT_TONNE            =5          # from enum EpfcMassUnitType
	EpfcMassUnitType_nil          =6          # from enum EpfcMassUnitType
	EpfcMTL_PROP_COMPRESSION_ULTIMATE_STRESS=29         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_COMPRESSION_ULTIMATE_STRESS_SC1=5          # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_COMPRESSION_ULTIMATE_STRESS_SC2=6          # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_COST_TYPE        =51         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_EMISSIVITY       =38         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_EXP_LAW_EXPONENT =60         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_FATIGUE_CUT_OFF_CYCLES=52         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_FATIGUE_STRENGTH_REDUCTION_FACTOR=0          # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_HARDENING        =56         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_HARDENING_LIMIT  =61         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_HARDNESS         =33         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_INITIAL_BEND_Y_FACTOR=34         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MASS_DENSITY     =26         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MECHANISMS_DAMPING=63         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_C01   =41         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_C02   =42         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_C10   =43         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_C11   =44         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_C20   =45         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_C30   =46         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_D     =47         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_D1    =48         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_D2    =49         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_D3    =50         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_LM    =40         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODEL_COEF_MU    =39         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_MODIFIED_MODULUS =58         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_POISSON_RATIO    =25         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_POISSON_RATIO_NU21=7          # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_POISSON_RATIO_NU31=8          # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_POISSON_RATIO_NU32=9          # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_POWER_LAW_EXPONENT=59         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_SHEAR_MODULUS    =35         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_SHEAR_MODULUS_G12=13         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_SHEAR_MODULUS_G13=14         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_SHEAR_MODULUS_G23=15         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_SHEAR_ULTIMATE_STRESS=30         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_SPECIFIC_HEAT    =32         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_STRESS_LIMIT_FOR_COMPRESSION=54         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_STRESS_LIMIT_FOR_FATIGUE=22         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_STRESS_LIMIT_FOR_SHEAR=55         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_STRESS_LIMIT_FOR_TENSION=53         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_STRUCTURAL_DAMPING_COEFFICIENT=37         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_TANGENT_MODULUS  =57         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_TEMPERATURE      =23         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_TENSILE_ULTIMATE_STRESS=28         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_TENSILE_ULTIMATE_STRESS_ST1=3          # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_TENSILE_ULTIMATE_STRESS_ST2=4          # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_TENSILE_YIELD_STRESS=2          # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_THERMAL_CONDUCTIVITY=31         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_THERMAL_CONDUCTIVITY_K1=19         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_THERMAL_CONDUCTIVITY_K2=20         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_THERMAL_CONDUCTIVITY_K3=21         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_THERMAL_EXPANSION_COEFFICIENT=27         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_THERMAL_EXPANSION_COEFFICIENT_A1=16         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_THERMAL_EXPANSION_COEFFICIENT_A2=17         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_THERMAL_EXPANSION_COEFFICIENT_A3=18         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_THERMAL_SOFTENING_COEF=62         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_THERM_EXPANSION_REF_TEMPERATURE=36         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_TSAI_WU_INTERACTION_TERM_F12=1          # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_YOUNG_MODULUS    =24         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_YOUNG_MODULUS_E1 =10         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_YOUNG_MODULUS_E2 =11         # from enum EpfcMaterialPropertyType
	EpfcMTL_PROP_YOUNG_MODULUS_E3 =12         # from enum EpfcMaterialPropertyType
	EpfcMaterialPropertyType_nil  =64         # from enum EpfcMaterialPropertyType
	EpfcMTL_ISOTROPIC             =0          # from enum EpfcMaterialType
	EpfcMTL_ORTHOTROPIC           =1          # from enum EpfcMaterialType
	EpfcMTL_TRANSVERSELY_ISOTROPIC=2          # from enum EpfcMaterialType
	EpfcMaterialType_nil          =3          # from enum EpfcMaterialType
	EpfcMESSAGE_BUTTON_ABORT      =4          # from enum EpfcMessageButton
	EpfcMESSAGE_BUTTON_CANCEL     =1          # from enum EpfcMessageButton
	EpfcMESSAGE_BUTTON_CONFIRM    =7          # from enum EpfcMessageButton
	EpfcMESSAGE_BUTTON_IGNORE     =6          # from enum EpfcMessageButton
	EpfcMESSAGE_BUTTON_NO         =3          # from enum EpfcMessageButton
	EpfcMESSAGE_BUTTON_OK         =0          # from enum EpfcMessageButton
	EpfcMESSAGE_BUTTON_RETRY      =5          # from enum EpfcMessageButton
	EpfcMESSAGE_BUTTON_YES        =2          # from enum EpfcMessageButton
	EpfcMessageButton_nil         =8          # from enum EpfcMessageButton
	EpfcMESSAGE_ERROR             =0          # from enum EpfcMessageDialogType
	EpfcMESSAGE_INFO              =1          # from enum EpfcMessageDialogType
	EpfcMESSAGE_QUESTION          =3          # from enum EpfcMessageDialogType
	EpfcMESSAGE_WARNING           =2          # from enum EpfcMessageDialogType
	EpfcMessageDialogType_nil     =4          # from enum EpfcMessageDialogType
	EpfcMODELCHECK_GRAPHICS       =0          # from enum EpfcModelCheckMode
	EpfcMODELCHECK_NO_GRAPHICS    =1          # from enum EpfcModelCheckMode
	EpfcModelCheckMode_nil        =2          # from enum EpfcModelCheckMode
	EpfcITEM_AXIS                 =4          # from enum EpfcModelItemType
	EpfcITEM_COORD_SYS            =3          # from enum EpfcModelItemType
	EpfcITEM_CURVE                =7          # from enum EpfcModelItemType
	EpfcITEM_DIMENSION            =10         # from enum EpfcModelItemType
	EpfcITEM_DTL_ENTITY           =15         # from enum EpfcModelItemType
	EpfcITEM_DTL_GROUP            =17         # from enum EpfcModelItemType
	EpfcITEM_DTL_NOTE             =16         # from enum EpfcModelItemType
	EpfcITEM_DTL_OLE_OBJECT       =20         # from enum EpfcModelItemType
	EpfcITEM_DTL_SYM_DEFINITION   =18         # from enum EpfcModelItemType
	EpfcITEM_DTL_SYM_INSTANCE     =19         # from enum EpfcModelItemType
	EpfcITEM_EDGE                 =2          # from enum EpfcModelItemType
	EpfcITEM_EDGE_END             =24         # from enum EpfcModelItemType
	EpfcITEM_EDGE_START           =22         # from enum EpfcModelItemType
	EpfcITEM_EXPLODED_STATE       =21         # from enum EpfcModelItemType
	EpfcITEM_FEATURE              =0          # from enum EpfcModelItemType
	EpfcITEM_LAYER                =8          # from enum EpfcModelItemType
	EpfcITEM_LOG_EDGE             =23         # from enum EpfcModelItemType
	EpfcITEM_NOTE                 =9          # from enum EpfcModelItemType
	EpfcITEM_POINT                =5          # from enum EpfcModelItemType
	EpfcITEM_QUILT                =6          # from enum EpfcModelItemType
	EpfcITEM_REF_DIMENSION        =11         # from enum EpfcModelItemType
	EpfcITEM_SIMPREP              =12         # from enum EpfcModelItemType
	EpfcITEM_SOLID_GEOMETRY       =13         # from enum EpfcModelItemType
	EpfcITEM_SURFACE              =1          # from enum EpfcModelItemType
	EpfcITEM_TABLE                =14         # from enum EpfcModelItemType
	EpfcModelItemType_nil         =25         # from enum EpfcModelItemType
	EpfcMDL_2D_SECTION            =3          # from enum EpfcModelType
	EpfcMDL_ASSEMBLY              =0          # from enum EpfcModelType
	EpfcMDL_DIAGRAM               =9          # from enum EpfcModelType
	EpfcMDL_DRAWING               =2          # from enum EpfcModelType
	EpfcMDL_DWG_FORMAT            =5          # from enum EpfcModelType
	EpfcMDL_LAYOUT                =4          # from enum EpfcModelType
	EpfcMDL_MARKUP                =8          # from enum EpfcModelType
	EpfcMDL_MFG                   =6          # from enum EpfcModelType
	EpfcMDL_PART                  =1          # from enum EpfcModelType
	EpfcMDL_REPORT                =7          # from enum EpfcModelType
	EpfcModelType_nil             =10         # from enum EpfcModelType
	EpfcMOUSE_BTN_ANY             =4          # from enum EpfcMouseButton
	EpfcMOUSE_BTN_LEFT            =0          # from enum EpfcMouseButton
	EpfcMOUSE_BTN_LEFT_DOUBLECLICK=3          # from enum EpfcMouseButton
	EpfcMOUSE_BTN_MIDDLE          =1          # from enum EpfcMouseButton
	EpfcMOUSE_BTN_MOVE            =5          # from enum EpfcMouseButton
	EpfcMOUSE_BTN_RIGHT           =2          # from enum EpfcMouseButton
	EpfcMouseButton_nil           =6          # from enum EpfcMouseButton
	EpfcIMPORT_NEW_ACIS           =11         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_CADDS          =3          # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_CATIA_CGR      =18         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_CATIA_MODEL    =9          # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_CATIA_PART     =14         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_CATIA_PRODUCT  =15         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_CATIA_SESSION  =8          # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_CC             =24         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_DXF            =10         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_ICEM           =13         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_IGES           =0          # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_INVENTOR_ASSEM =23         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_INVENTOR_PART  =22         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_JT             =19         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_NEUTRAL        =2          # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_PARASOLID      =12         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_POLTXT         =7          # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_PRODUCTVIEW    =17         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_STEP           =4          # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_STL            =5          # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_SW_ASSEM       =21         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_SW_PART        =20         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_UG             =16         # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_VDA            =1          # from enum EpfcNewModelImportType
	EpfcIMPORT_NEW_VRML           =6          # from enum EpfcNewModelImportType
	EpfcNewModelImportType_nil    =25         # from enum EpfcNewModelImportType
	EpfcOFFSET_SIDE_ONE           =0          # from enum EpfcOffsetCurveDirection
	EpfcOFFSET_SIDE_TWO           =1          # from enum EpfcOffsetCurveDirection
	EpfcOffsetCurveDirection_nil  =2          # from enum EpfcOffsetCurveDirection
	EpfcADD_OPERATION             =1          # from enum EpfcOperationType
	EpfcCUT_OPERATION             =0          # from enum EpfcOperationType
	EpfcOperationType_nil         =2          # from enum EpfcOperationType
	EpfcORIENTHINT_ARC_ANGLE      =6          # from enum EpfcOrientationHint
	EpfcORIENTHINT_ARC_LENGTH     =7          # from enum EpfcOrientationHint
	EpfcORIENTHINT_ELLIPSE_RADIUS1=4          # from enum EpfcOrientationHint
	EpfcORIENTHINT_ELLIPSE_RADIUS2=5          # from enum EpfcOrientationHint
	EpfcORIENTHINT_HORIZONTAL     =1          # from enum EpfcOrientationHint
	EpfcORIENTHINT_LINE_TO_TANGENT_CURVE_ANGLE=8          # from enum EpfcOrientationHint
	EpfcORIENTHINT_NONE           =0          # from enum EpfcOrientationHint
	EpfcORIENTHINT_SLANTED        =3          # from enum EpfcOrientationHint
	EpfcORIENTHINT_VERTICAL       =2          # from enum EpfcOrientationHint
	EpfcOrientationHint_nil       =9          # from enum EpfcOrientationHint
	EpfcPDFColorDepth_nil         =3          # from enum EpfcPDFColorDepth
	EpfcPDF_CD_COLOR              =0          # from enum EpfcPDFColorDepth
	EpfcPDF_CD_GRAY               =1          # from enum EpfcPDFColorDepth
	EpfcPDF_CD_MONO               =2          # from enum EpfcPDFColorDepth
	EpfcPDFExportMode_nil         =4          # from enum EpfcPDFExportMode
	EpfcPDF_2D_DRAWING            =0          # from enum EpfcPDFExportMode
	EpfcPDF_3D_AS_NAMED_VIEWS     =1          # from enum EpfcPDFExportMode
	EpfcPDF_3D_AS_U3D             =3          # from enum EpfcPDFExportMode
	EpfcPDF_3D_AS_U3D_PDF         =2          # from enum EpfcPDFExportMode
	EpfcPDFFontStrokeMode_nil     =2          # from enum EpfcPDFFontStrokeMode
	EpfcPDF_STROKE_ALL_FONTS      =0          # from enum EpfcPDFFontStrokeMode
	EpfcPDF_USE_TRUE_TYPE_FONTS   =1          # from enum EpfcPDFFontStrokeMode
	EpfcPDFHiddenLineMode_nil     =2          # from enum EpfcPDFHiddenLineMode
	EpfcPDF_HLM_DASHED            =1          # from enum EpfcPDFHiddenLineMode
	EpfcPDF_HLM_SOLID             =0          # from enum EpfcPDFHiddenLineMode
	EpfcPDFLayerMode_nil          =3          # from enum EpfcPDFLayerMode
	EpfcPDF_LAYERS_ALL            =0          # from enum EpfcPDFLayerMode
	EpfcPDF_LAYERS_NONE           =2          # from enum EpfcPDFLayerMode
	EpfcPDF_LAYERS_VISIBLE        =1          # from enum EpfcPDFLayerMode
	EpfcPDFLinecap_nil            =3          # from enum EpfcPDFLinecap
	EpfcPDF_LINECAP_BUTT          =0          # from enum EpfcPDFLinecap
	EpfcPDF_LINECAP_PROJECTING_SQUARE=2          # from enum EpfcPDFLinecap
	EpfcPDF_LINECAP_ROUND         =1          # from enum EpfcPDFLinecap
	EpfcPDFLinejoin_nil           =3          # from enum EpfcPDFLinejoin
	EpfcPDF_LINEJOIN_BEVEL        =2          # from enum EpfcPDFLinejoin
	EpfcPDF_LINEJOIN_MITER        =0          # from enum EpfcPDFLinejoin
	EpfcPDF_LINEJOIN_ROUND        =1          # from enum EpfcPDFLinejoin
	EpfcPDFOPT_ADD_VIEWS          =42         # from enum EpfcPDFOptionType
	EpfcPDFOPT_ALLOW_ACCESSIBILITY=24         # from enum EpfcPDFOptionType
	EpfcPDFOPT_ALLOW_COPYING      =23         # from enum EpfcPDFOptionType
	EpfcPDFOPT_ALLOW_MODE         =22         # from enum EpfcPDFOptionType
	EpfcPDFOPT_ALLOW_PRINTING     =20         # from enum EpfcPDFOptionType
	EpfcPDFOPT_ALLOW_PRINTING_MODE=21         # from enum EpfcPDFOptionType
	EpfcPDFOPT_AUTHOR             =14         # from enum EpfcPDFOptionType
	EpfcPDFOPT_BACKGROUND_COLOR_BLUE=41         # from enum EpfcPDFOptionType
	EpfcPDFOPT_BACKGROUND_COLOR_GREEN=40         # from enum EpfcPDFOptionType
	EpfcPDFOPT_BACKGROUND_COLOR_RED=39         # from enum EpfcPDFOptionType
	EpfcPDFOPT_BOOKMARK_FLAG_NOTES=12         # from enum EpfcPDFOptionType
	EpfcPDFOPT_BOOKMARK_SHEETS    =11         # from enum EpfcPDFOptionType
	EpfcPDFOPT_BOOKMARK_VIEWS     =10         # from enum EpfcPDFOptionType
	EpfcPDFOPT_BOOKMARK_ZONES     =9          # from enum EpfcPDFOptionType
	EpfcPDFOPT_COLOR_DEPTH        =1          # from enum EpfcPDFOptionType
	EpfcPDFOPT_EXPORT_MODE        =30         # from enum EpfcPDFOptionType
	EpfcPDFOPT_FONT_STROKE        =0          # from enum EpfcPDFOptionType
	EpfcPDFOPT_HEIGHT             =34         # from enum EpfcPDFOptionType
	EpfcPDFOPT_HIDDENLINE_MODE    =2          # from enum EpfcPDFOptionType
	EpfcPDFOPT_HYPERLINKS         =8          # from enum EpfcPDFOptionType
	EpfcPDFOPT_KEYWORDS           =16         # from enum EpfcPDFOptionType
	EpfcPDFOPT_LAUNCH_VIEWER      =5          # from enum EpfcPDFOptionType
	EpfcPDFOPT_LAYER_MODE         =6          # from enum EpfcPDFOptionType
	EpfcPDFOPT_LEFT_MARGIN        =38         # from enum EpfcPDFOptionType
	EpfcPDFOPT_LIGHT_DEFAULT      =31         # from enum EpfcPDFOptionType
	EpfcPDFOPT_LINECAP            =26         # from enum EpfcPDFOptionType
	EpfcPDFOPT_LINEJOIN           =27         # from enum EpfcPDFOptionType
	EpfcPDFOPT_MASTER_PASSWORD    =18         # from enum EpfcPDFOptionType
	EpfcPDFOPT_ORIENTATION        =36         # from enum EpfcPDFOptionType
	EpfcPDFOPT_PARAM_MODE         =7          # from enum EpfcPDFOptionType
	EpfcPDFOPT_PASSWORD_TO_OPEN   =17         # from enum EpfcPDFOptionType
	EpfcPDFOPT_PDF_SAVE           =45         # from enum EpfcPDFOptionType
	EpfcPDFOPT_PENTABLE           =25         # from enum EpfcPDFOptionType
	EpfcPDFOPT_RASTER_DPI         =4          # from enum EpfcPDFOptionType
	EpfcPDFOPT_RENDER_STYLE_DEFAULT=32         # from enum EpfcPDFOptionType
	EpfcPDFOPT_RESTRICT_OPERATIONS=19         # from enum EpfcPDFOptionType
	EpfcPDFOPT_SEARCHABLE_TEXT    =3          # from enum EpfcPDFOptionType
	EpfcPDFOPT_SELECTED_VIEW      =44         # from enum EpfcPDFOptionType
	EpfcPDFOPT_SHEETS             =28         # from enum EpfcPDFOptionType
	EpfcPDFOPT_SHEET_RANGE        =29         # from enum EpfcPDFOptionType
	EpfcPDFOPT_SIZE               =33         # from enum EpfcPDFOptionType
	EpfcPDFOPT_SUBJECT            =15         # from enum EpfcPDFOptionType
	EpfcPDFOPT_TITLE              =13         # from enum EpfcPDFOptionType
	EpfcPDFOPT_TOP_MARGIN         =37         # from enum EpfcPDFOptionType
	EpfcPDFOPT_VIEW_TO_EXPORT     =43         # from enum EpfcPDFOptionType
	EpfcPDFOPT_WIDTH              =35         # from enum EpfcPDFOptionType
	EpfcPDFOptionType_nil         =46         # from enum EpfcPDFOptionType
	EpfcPDFParameterMode_nil      =3          # from enum EpfcPDFParameterMode
	EpfcPDF_PARAMS_ALL            =0          # from enum EpfcPDFParameterMode
	EpfcPDF_PARAMS_DESIGNATED     =1          # from enum EpfcPDFParameterMode
	EpfcPDF_PARAMS_NONE           =2          # from enum EpfcPDFParameterMode
	EpfcPDFPrintingMode_nil       =2          # from enum EpfcPDFPrintingMode
	EpfcPDF_PRINTING_HIGH_RES     =1          # from enum EpfcPDFPrintingMode
	EpfcPDF_PRINTING_LOW_RES      =0          # from enum EpfcPDFPrintingMode
	EpfcPDFRestrictOperationsMode_nil=5          # from enum EpfcPDFRestrictOperationsMode
	EpfcPDF_RESTRICT_COMMENT_FORM_SIGNING=3          # from enum EpfcPDFRestrictOperationsMode
	EpfcPDF_RESTRICT_EXTRACTING   =4          # from enum EpfcPDFRestrictOperationsMode
	EpfcPDF_RESTRICT_FORMS_SIGNING=1          # from enum EpfcPDFRestrictOperationsMode
	EpfcPDF_RESTRICT_INSERT_DELETE_ROTATE=2          # from enum EpfcPDFRestrictOperationsMode
	EpfcPDF_RESTRICT_NONE         =0          # from enum EpfcPDFRestrictOperationsMode
	EpfcPDFSaveMode_nil           =2          # from enum EpfcPDFSaveMode
	EpfcPDF_ARCHIVE_1             =0          # from enum EpfcPDFSaveMode
	EpfcPDF_FULL                  =1          # from enum EpfcPDFSaveMode
	EpfcPDFSelectedViewMode_nil   =3          # from enum EpfcPDFSelectedViewMode
	EpfcPDF_VIEW_SELECT_ALL       =1          # from enum EpfcPDFSelectedViewMode
	EpfcPDF_VIEW_SELECT_BY_NAME   =2          # from enum EpfcPDFSelectedViewMode
	EpfcPDF_VIEW_SELECT_CURRENT   =0          # from enum EpfcPDFSelectedViewMode
	EpfcPDFU3DLightingMode_nil    =11         # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_BLUE        =6          # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_BRIGHT      =3          # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_CAD         =9          # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_CUBE        =8          # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_DAY         =2          # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_HEADLAMP    =10         # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_NIGHT       =5          # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_NONE        =0          # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_PRIMARY     =4          # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_RED         =7          # from enum EpfcPDFU3DLightingMode
	EpfcPDF_U3D_LIGHT_WHITE       =1          # from enum EpfcPDFU3DLightingMode
	EpfcPDFU3DRenderMode_nil      =15         # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_BOUNDING_BOX=0          # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_HIDDEN_WIREFRAME=14         # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_ILLUSTRATION=11         # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_SHADED_ILLUSTRATION=13         # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_SHADED_VERTICES=4          # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_SHADED_WIREFRAME=6          # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_SOLID      =7          # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_SOLID_OUTLINE=12         # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_SOLID_WIREFRAME=9          # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_TRANSPARENT=8          # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_TRANSPARENT_BOUNDING_BOX=1          # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_TRANSPARENT_BOUNDING_BOX_OUTLINE=2          # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_TRANSPARENT_WIREFRAME=10         # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_VERTICES   =3          # from enum EpfcPDFU3DRenderMode
	EpfcPDF_U3D_RENDER_WIREFRAME  =5          # from enum EpfcPDFU3DRenderMode
	EpfcDWGTABLE_FULL             =1          # from enum EpfcParamMode
	EpfcDWGTABLE_NORMAL           =0          # from enum EpfcParamMode
	EpfcParamMode_nil             =2          # from enum EpfcParamMode
	EpfcALL_PARAMS                =5          # from enum EpfcParamType
	EpfcDIMTOL_PARAM              =3          # from enum EpfcParamType
	EpfcDIM_PARAM                 =1          # from enum EpfcParamType
	EpfcGTOL_PARAM                =6          # from enum EpfcParamType
	EpfcPATTERN_PARAM             =2          # from enum EpfcParamType
	EpfcParamType_nil             =8          # from enum EpfcParamType
	EpfcREFDIM_PARAM              =4          # from enum EpfcParamType
	EpfcSURFFIN_PARAM             =7          # from enum EpfcParamType
	EpfcUSER_PARAM                =0          # from enum EpfcParamType
	EpfcPARAM_BOOLEAN             =2          # from enum EpfcParamValueType
	EpfcPARAM_DOUBLE              =3          # from enum EpfcParamValueType
	EpfcPARAM_INTEGER             =1          # from enum EpfcParamValueType
	EpfcPARAM_NOTE                =4          # from enum EpfcParamValueType
	EpfcPARAM_NOT_SET             =6          # from enum EpfcParamValueType
	EpfcPARAM_STRING              =0          # from enum EpfcParamValueType
	EpfcPARAM_VOID                =5          # from enum EpfcParamValueType
	EpfcParamValueType_nil        =7          # from enum EpfcParamValueType
	EpfcPARAMDRIVER_FUNCTION      =1          # from enum EpfcParameterDriverType
	EpfcPARAMDRIVER_PARAM         =0          # from enum EpfcParameterDriverType
	EpfcPARAMDRIVER_RELATION      =2          # from enum EpfcParameterDriverType
	EpfcParameterDriverType_nil   =3          # from enum EpfcParameterDriverType
	EpfcPARAMLIMIT_GREATER_THAN   =2          # from enum EpfcParameterLimitType
	EpfcPARAMLIMIT_GREATER_THAN_OR_EQUAL=3          # from enum EpfcParameterLimitType
	EpfcPARAMLIMIT_LESS_THAN      =0          # from enum EpfcParameterLimitType
	EpfcPARAMLIMIT_LESS_THAN_OR_EQUAL=1          # from enum EpfcParameterLimitType
	EpfcPARAMLIMIT_UNLIMITED      =4          # from enum EpfcParameterLimitType
	EpfcParameterLimitType_nil    =5          # from enum EpfcParameterLimitType
	EpfcPARAMSELECT_ALLOW_SUBITEM_SELECTION=12         # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_ASM           =2          # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_COMPONENT     =11         # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_COMPOSITE_CURVE=8          # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_CURVE         =7          # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_EDGE          =4          # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_FEATURE       =3          # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_INHERITED     =9          # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_MODEL         =0          # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_PART          =1          # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_QUILT         =6          # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_SKELETON      =10         # from enum EpfcParameterSelectionContext
	EpfcPARAMSELECT_SURFACE       =5          # from enum EpfcParameterSelectionContext
	EpfcParameterSelectionContext_nil=13         # from enum EpfcParameterSelectionContext
	EpfcPLACE_INSIDE              =0          # from enum EpfcPlacement
	EpfcPLACE_ON_BOUNDARY         =1          # from enum EpfcPlacement
	EpfcPLACE_OUTSIDE             =2          # from enum EpfcPlacement
	EpfcPlacement_nil             =3          # from enum EpfcPlacement
	EpfcPLOT_RANGE_ALL            =0          # from enum EpfcPlotPageRange
	EpfcPLOT_RANGE_CURRENT        =1          # from enum EpfcPlotPageRange
	EpfcPLOT_RANGE_OF_PAGES       =2          # from enum EpfcPlotPageRange
	EpfcPlotPageRange_nil         =3          # from enum EpfcPlotPageRange
	EpfcA0SIZEPLOT                =9          # from enum EpfcPlotPaperSize
	EpfcA1SIZEPLOT                =8          # from enum EpfcPlotPaperSize
	EpfcA2SIZEPLOT                =7          # from enum EpfcPlotPaperSize
	EpfcA3SIZEPLOT                =6          # from enum EpfcPlotPaperSize
	EpfcA4SIZEPLOT                =5          # from enum EpfcPlotPaperSize
	EpfcASIZEPLOT                 =0          # from enum EpfcPlotPaperSize
	EpfcBSIZEPLOT                 =1          # from enum EpfcPlotPaperSize
	EpfcCSIZEPLOT                 =2          # from enum EpfcPlotPaperSize
	EpfcDSIZEPLOT                 =3          # from enum EpfcPlotPaperSize
	EpfcESIZEPLOT                 =4          # from enum EpfcPlotPaperSize
	EpfcFSIZEPLOT                 =10         # from enum EpfcPlotPaperSize
	EpfcPlotPaperSize_nil         =13         # from enum EpfcPlotPaperSize
	EpfcVARIABLESIZEPLOT          =11         # from enum EpfcPlotPaperSize
	EpfcVARIABLESIZE_IN_MM_PLOT   =12         # from enum EpfcPlotPaperSize
	EpfcPRINT_SAVE_APPEND_TO_FILE =3          # from enum EpfcPrintSaveMethod
	EpfcPRINT_SAVE_MULTIPLE_FILE  =2          # from enum EpfcPrintSaveMethod
	EpfcPRINT_SAVE_NULL           =0          # from enum EpfcPrintSaveMethod
	EpfcPRINT_SAVE_SINGLE_FILE    =1          # from enum EpfcPrintSaveMethod
	EpfcPrintSaveMethod_nil       =4          # from enum EpfcPrintSaveMethod
	EpfcPRINT_ALL_SHEETS          =1          # from enum EpfcPrintSheets
	EpfcPRINT_CURRENT_SHEET       =0          # from enum EpfcPrintSheets
	EpfcPRINT_SELECTED_SHEETS     =2          # from enum EpfcPrintSheets
	EpfcPrintSheets_nil           =3          # from enum EpfcPrintSheets
	EpfcPV_FORMAT_ED              =1          # from enum EpfcProductViewFormat
	EpfcPV_FORMAT_EDZ             =2          # from enum EpfcProductViewFormat
	EpfcPV_FORMAT_PVS             =0          # from enum EpfcProductViewFormat
	EpfcPV_FORMAT_PVZ             =3          # from enum EpfcProductViewFormat
	EpfcProductViewFormat_nil     =4          # from enum EpfcProductViewFormat
	EpfcRASTERDEPTH_24            =1          # from enum EpfcRasterDepth
	EpfcRASTERDEPTH_8             =0          # from enum EpfcRasterDepth
	EpfcRasterDepth_nil           =2          # from enum EpfcRasterDepth
	EpfcRASTER_BMP                =0          # from enum EpfcRasterType
	EpfcRASTER_EPS                =2          # from enum EpfcRasterType
	EpfcRASTER_JPEG               =3          # from enum EpfcRasterType
	EpfcRASTER_TIFF               =1          # from enum EpfcRasterType
	EpfcRasterType_nil            =4          # from enum EpfcRasterType
	EpfcFILE_INCLUDE_ALL          =0          # from enum EpfcRelCriterion
	EpfcFILE_INCLUDE_NONE         =2          # from enum EpfcRelCriterion
	EpfcFILE_INCLUDE_REQUIRED     =1          # from enum EpfcRelCriterion
	EpfcRelCriterion_nil          =3          # from enum EpfcRelCriterion
	EpfcPARAMSELECT_ENUMERATION   =0          # from enum EpfcRestrictionType
	EpfcPARAMSELECT_RANGE         =1          # from enum EpfcRestrictionType
	EpfcRestrictionType_nil       =2          # from enum EpfcRestrictionType
	EpfcROTATE_180                =1          # from enum EpfcRotationDegree
	EpfcROTATE_270                =2          # from enum EpfcRotationDegree
	EpfcROTATE_90                 =0          # from enum EpfcRotationDegree
	EpfcRotationDegree_nil        =3          # from enum EpfcRotationDegree
	EpfcSERVER_AUTORESOLVE_IGNORE =1          # from enum EpfcServerAutoresolveOption
	EpfcSERVER_AUTORESOLVE_UPDATE_IGNORE=2          # from enum EpfcServerAutoresolveOption
	EpfcSERVER_DONT_AUTORESOLVE   =0          # from enum EpfcServerAutoresolveOption
	EpfcServerAutoresolveOption_nil=3          # from enum EpfcServerAutoresolveOption
	EpfcSERVER_DEPENDENCY_ALL     =0          # from enum EpfcServerDependency
	EpfcSERVER_DEPENDENCY_NONE    =2          # from enum EpfcServerDependency
	EpfcSERVER_DEPENDENCY_REQUIRED=1          # from enum EpfcServerDependency
	EpfcServerDependency_nil      =3          # from enum EpfcServerDependency
	EpfcSERVER_INCLUDE_ALL        =0          # from enum EpfcServerIncludeInstances
	EpfcSERVER_INCLUDE_NONE       =2          # from enum EpfcServerIncludeInstances
	EpfcSERVER_INCLUDE_SELECTED   =1          # from enum EpfcServerIncludeInstances
	EpfcServerIncludeInstances_nil=3          # from enum EpfcServerIncludeInstances
	EpfcOBJ_LOCK_STAT_HARDLOCK    =2          # from enum EpfcServerObjectLockStatus
	EpfcOBJ_LOCK_STAT_SOFTLOCK    =3          # from enum EpfcServerObjectLockStatus
	EpfcOBJ_LOCK_STAT_UNLOCKED    =1          # from enum EpfcServerObjectLockStatus
	EpfcOBJ_LOCK_STAT_UNSET       =0          # from enum EpfcServerObjectLockStatus
	EpfcServerObjectLockStatus_nil=4          # from enum EpfcServerObjectLockStatus
	EpfcORIENT_LANDSCAPE          =1          # from enum EpfcSheetOrientation
	EpfcORIENT_PORTRAIT           =0          # from enum EpfcSheetOrientation
	EpfcSheetOrientation_nil      =2          # from enum EpfcSheetOrientation
	EpfcSWFACETED_LIGHTWEIGHT_PART=3          # from enum EpfcShrinkwrapFacetedFormat
	EpfcSWFACETED_PART            =0          # from enum EpfcShrinkwrapFacetedFormat
	EpfcSWFACETED_STL             =1          # from enum EpfcShrinkwrapFacetedFormat
	EpfcSWFACETED_VRML            =2          # from enum EpfcShrinkwrapFacetedFormat
	EpfcShrinkwrapFacetedFormat_nil=4          # from enum EpfcShrinkwrapFacetedFormat
	EpfcSWCREATE_FACETED_SOLID    =1          # from enum EpfcShrinkwrapMethod
	EpfcSWCREATE_MERGED_SOLID     =2          # from enum EpfcShrinkwrapMethod
	EpfcSWCREATE_SURF_SUBSET      =0          # from enum EpfcShrinkwrapMethod
	EpfcShrinkwrapMethod_nil      =3          # from enum EpfcShrinkwrapMethod
	EpfcSIMPREP_BOUNDBOX          =7          # from enum EpfcSimpRepActionType
	EpfcSIMPREP_DEFENV            =8          # from enum EpfcSimpRepActionType
	EpfcSIMPREP_EXCLUDE           =2          # from enum EpfcSimpRepActionType
	EpfcSIMPREP_GEOM              =4          # from enum EpfcSimpRepActionType
	EpfcSIMPREP_GRAPHICS          =5          # from enum EpfcSimpRepActionType
	EpfcSIMPREP_INCLUDE           =1          # from enum EpfcSimpRepActionType
	EpfcSIMPREP_NONE              =9          # from enum EpfcSimpRepActionType
	EpfcSIMPREP_REVERSE           =0          # from enum EpfcSimpRepActionType
	EpfcSIMPREP_SUBSTITUTE        =3          # from enum EpfcSimpRepActionType
	EpfcSIMPREP_SYMB              =6          # from enum EpfcSimpRepActionType
	EpfcSimpRepActionType_nil     =10         # from enum EpfcSimpRepActionType
	EpfcSIMPREP_BOUNDBOX_REP      =5          # from enum EpfcSimpRepType
	EpfcSIMPREP_DEFENV_REP        =6          # from enum EpfcSimpRepType
	EpfcSIMPREP_GEOM_REP          =3          # from enum EpfcSimpRepType
	EpfcSIMPREP_GRAPHICS_REP      =2          # from enum EpfcSimpRepType
	EpfcSIMPREP_MASTER_REP        =0          # from enum EpfcSimpRepType
	EpfcSIMPREP_SYMB_REP          =4          # from enum EpfcSimpRepType
	EpfcSIMPREP_USER_DEFINED      =1          # from enum EpfcSimpRepType
	EpfcSimpRepType_nil           =7          # from enum EpfcSimpRepType
	EpfcCURVE_BOTH_SIDES          =2          # from enum EpfcSplitCurveSide
	EpfcCURVE_SIDE_ONE            =0          # from enum EpfcSplitCurveSide
	EpfcCURVE_SIDE_TWO            =1          # from enum EpfcSplitCurveSide
	EpfcSplitCurveSide_nil        =3          # from enum EpfcSplitCurveSide
	EpfcCOLOR_BACKGROUND          =3          # from enum EpfcStdColor
	EpfcCOLOR_CURVE               =10         # from enum EpfcStdColor
	EpfcCOLOR_DATUM               =16         # from enum EpfcStdColor
	EpfcCOLOR_DIMMED              =6          # from enum EpfcStdColor
	EpfcCOLOR_DRAWING             =2          # from enum EpfcStdColor
	EpfcCOLOR_EDGE_HIGHLIGHT      =5          # from enum EpfcStdColor
	EpfcCOLOR_ERROR               =7          # from enum EpfcStdColor
	EpfcCOLOR_HALF_TONE           =4          # from enum EpfcStdColor
	EpfcCOLOR_HIGHLIGHT           =1          # from enum EpfcStdColor
	EpfcCOLOR_LETTER              =0          # from enum EpfcStdColor
	EpfcCOLOR_LWW                 =18         # from enum EpfcStdColor
	EpfcCOLOR_MAX                 =19         # from enum EpfcStdColor
	EpfcCOLOR_PRESEL_HIGHLIGHT    =11         # from enum EpfcStdColor
	EpfcCOLOR_PREVIEW             =14         # from enum EpfcStdColor
	EpfcCOLOR_QUILT               =17         # from enum EpfcStdColor
	EpfcCOLOR_SECONDARY_PREVIEW   =15         # from enum EpfcStdColor
	EpfcCOLOR_SECONDARY_SELECTED  =13         # from enum EpfcStdColor
	EpfcCOLOR_SELECTED            =12         # from enum EpfcStdColor
	EpfcCOLOR_SHEETMETAL          =9          # from enum EpfcStdColor
	EpfcCOLOR_WARNING             =8          # from enum EpfcStdColor
	EpfcStdColor_nil              =20         # from enum EpfcStdColor
	EpfcLINE_CENTERLINE           =2          # from enum EpfcStdLineStyle
	EpfcLINE_CTRL_L_L             =6          # from enum EpfcStdLineStyle
	EpfcLINE_CTRL_MID_L           =10         # from enum EpfcStdLineStyle
	EpfcLINE_CTRL_S_L             =5          # from enum EpfcStdLineStyle
	EpfcLINE_CTRL_S_S             =7          # from enum EpfcStdLineStyle
	EpfcLINE_DASH                 =4          # from enum EpfcStdLineStyle
	EpfcLINE_DASH_S_S             =8          # from enum EpfcStdLineStyle
	EpfcLINE_DOTTED               =1          # from enum EpfcStdLineStyle
	EpfcLINE_INTMIT_LWW_HIDDEN    =11         # from enum EpfcStdLineStyle
	EpfcLINE_PDFHIDDEN_LINESTYLE  =12         # from enum EpfcStdLineStyle
	EpfcLINE_PHANTOM              =3          # from enum EpfcStdLineStyle
	EpfcLINE_PHANTOM_S_S          =9          # from enum EpfcStdLineStyle
	EpfcLINE_SOLID                =0          # from enum EpfcStdLineStyle
	EpfcStdLineStyle_nil          =13         # from enum EpfcStdLineStyle
	EpfcSUBST_ASM_REP             =2          # from enum EpfcSubstType
	EpfcSUBST_ENVELOPE            =3          # from enum EpfcSubstType
	EpfcSUBST_INTERCHG            =0          # from enum EpfcSubstType
	EpfcSUBST_PRT_REP             =1          # from enum EpfcSubstType
	EpfcSubstType_nil             =4          # from enum EpfcSubstType
	EpfcSURFACEORIENT_INWARD      =2          # from enum EpfcSurfaceOrientation
	EpfcSURFACEORIENT_NONE        =0          # from enum EpfcSurfaceOrientation
	EpfcSURFACEORIENT_OUTWARD     =1          # from enum EpfcSurfaceOrientation
	EpfcSurfaceOrientation_nil    =3          # from enum EpfcSurfaceOrientation
	EpfcSURFACE_CONE              =2          # from enum EpfcSurfaceType
	EpfcSURFACE_COONS_PATCH       =8          # from enum EpfcSurfaceType
	EpfcSURFACE_CYLINDER          =1          # from enum EpfcSurfaceType
	EpfcSURFACE_CYLINDRICAL_SPLINE=11         # from enum EpfcSurfaceType
	EpfcSURFACE_FILLET            =7          # from enum EpfcSurfaceType
	EpfcSURFACE_FOREIGN           =13         # from enum EpfcSurfaceType
	EpfcSURFACE_NURBS             =10         # from enum EpfcSurfaceType
	EpfcSURFACE_PLANE             =0          # from enum EpfcSurfaceType
	EpfcSURFACE_REVOLVED          =5          # from enum EpfcSurfaceType
	EpfcSURFACE_RULED             =4          # from enum EpfcSurfaceType
	EpfcSURFACE_SPHERICAL_SPLINE  =12         # from enum EpfcSurfaceType
	EpfcSURFACE_SPLINE            =9          # from enum EpfcSurfaceType
	EpfcSURFACE_TABULATED_CYLINDER=6          # from enum EpfcSurfaceType
	EpfcSURFACE_TORUS             =3          # from enum EpfcSurfaceType
	EpfcSurfaceType_nil           =14         # from enum EpfcSurfaceType
	EpfcSYMDEFATTACH_FREE         =0          # from enum EpfcSymbolDefAttachmentType
	EpfcSYMDEFATTACH_LEFT_LEADER  =1          # from enum EpfcSymbolDefAttachmentType
	EpfcSYMDEFATTACH_NORMAL_TO_ITEM=5          # from enum EpfcSymbolDefAttachmentType
	EpfcSYMDEFATTACH_ON_ITEM      =4          # from enum EpfcSymbolDefAttachmentType
	EpfcSYMDEFATTACH_RADIAL_LEADER=3          # from enum EpfcSymbolDefAttachmentType
	EpfcSYMDEFATTACH_RIGHT_LEADER =2          # from enum EpfcSymbolDefAttachmentType
	EpfcSymbolDefAttachmentType_nil=6          # from enum EpfcSymbolDefAttachmentType
	EpfcSYMDEF_FIXED              =0          # from enum EpfcSymbolDefHeight
	EpfcSYMDEF_RELATIVE_TO_TEXT   =2          # from enum EpfcSymbolDefHeight
	EpfcSYMDEF_VARIABLE           =1          # from enum EpfcSymbolDefHeight
	EpfcSymbolDefHeight_nil       =3          # from enum EpfcSymbolDefHeight
	EpfcDTLSYMINST_ACTIVE_GROUPS  =1          # from enum EpfcSymbolGroupFilter
	EpfcDTLSYMINST_ALL_GROUPS     =0          # from enum EpfcSymbolGroupFilter
	EpfcDTLSYMINST_INACTIVE_GROUPS=2          # from enum EpfcSymbolGroupFilter
	EpfcSymbolGroupFilter_nil     =3          # from enum EpfcSymbolGroupFilter
	EpfcTABLESIZE_BY_LENGTH       =1          # from enum EpfcTableSizeType
	EpfcTABLESIZE_BY_NUM_CHARS    =0          # from enum EpfcTableSizeType
	EpfcTableSizeType_nil         =2          # from enum EpfcTableSizeType
	EpfcTANEDGE_CENTERLINE        =2          # from enum EpfcTangentEdgeDisplayStyle
	EpfcTANEDGE_DEFAULT           =0          # from enum EpfcTangentEdgeDisplayStyle
	EpfcTANEDGE_DIMMED            =4          # from enum EpfcTangentEdgeDisplayStyle
	EpfcTANEDGE_NONE              =1          # from enum EpfcTangentEdgeDisplayStyle
	EpfcTANEDGE_PHANTOM           =3          # from enum EpfcTangentEdgeDisplayStyle
	EpfcTANEDGE_SOLID             =5          # from enum EpfcTangentEdgeDisplayStyle
	EpfcTangentEdgeDisplayStyle_nil=6          # from enum EpfcTangentEdgeDisplayStyle
	EpfcTERM_ABNORMAL             =1          # from enum EpfcTerminationStatus
	EpfcTERM_EXIT                 =0          # from enum EpfcTerminationStatus
	EpfcTERM_SIGNAL               =2          # from enum EpfcTerminationStatus
	EpfcTerminationStatus_nil     =3          # from enum EpfcTerminationStatus
	EpfcTOLTABLE_BROKEN_EDGE      =1          # from enum EpfcToleranceTableType
	EpfcTOLTABLE_GENERAL          =0          # from enum EpfcToleranceTableType
	EpfcTOLTABLE_HOLES            =3          # from enum EpfcToleranceTableType
	EpfcTOLTABLE_SHAFTS           =2          # from enum EpfcToleranceTableType
	EpfcToleranceTableType_nil    =4          # from enum EpfcToleranceTableType
	EpfcUDFDEP_DRIVEN             =1          # from enum EpfcUDFDependencyType
	EpfcUDFDEP_INDEPENDENT        =0          # from enum EpfcUDFDependencyType
	EpfcUDFDependencyType_nil     =2          # from enum EpfcUDFDependencyType
	EpfcUDFDISPLAY_BLANK          =2          # from enum EpfcUDFDimensionDisplayType
	EpfcUDFDISPLAY_NORMAL         =0          # from enum EpfcUDFDimensionDisplayType
	EpfcUDFDISPLAY_READ_ONLY      =1          # from enum EpfcUDFDimensionDisplayType
	EpfcUDFDimensionDisplayType_nil=3          # from enum EpfcUDFDimensionDisplayType
	EpfcUDFORIENT_FLIP            =2          # from enum EpfcUDFOrientation
	EpfcUDFORIENT_INTERACTIVE     =0          # from enum EpfcUDFOrientation
	EpfcUDFORIENT_NO_FLIP         =1          # from enum EpfcUDFOrientation
	EpfcUDFOrientation_nil        =3          # from enum EpfcUDFOrientation
	EpfcUDFSCALE_CUSTOM           =2          # from enum EpfcUDFScaleType
	EpfcUDFSCALE_SAME_DIMS        =1          # from enum EpfcUDFScaleType
	EpfcUDFSCALE_SAME_SIZE        =0          # from enum EpfcUDFScaleType
	EpfcUDFScaleType_nil          =3          # from enum EpfcUDFScaleType
	EpfcUDFVARIANT_DIMENSION      =0          # from enum EpfcUDFVariantValueType
	EpfcUDFVARIANT_PATTERN_PARAM  =1          # from enum EpfcUDFVariantValueType
	EpfcUDFVariantValueType_nil   =2          # from enum EpfcUDFVariantValueType
	EpfcUNITCONVERT_SAME_DIMS     =0          # from enum EpfcUnitDimensionConversion
	EpfcUNITCONVERT_SAME_SIZE     =1          # from enum EpfcUnitDimensionConversion
	EpfcUnitDimensionConversion_nil=2          # from enum EpfcUnitDimensionConversion
	EpfcUNIT_SYSTEM_FORCE_LENGTH_TIME=1          # from enum EpfcUnitSystemType
	EpfcUNIT_SYSTEM_MASS_LENGTH_TIME=0          # from enum EpfcUnitSystemType
	EpfcUnitSystemType_nil        =2          # from enum EpfcUnitSystemType
	EpfcUNIT_ANGLE                =5          # from enum EpfcUnitType
	EpfcUNIT_FORCE                =2          # from enum EpfcUnitType
	EpfcUNIT_LENGTH               =0          # from enum EpfcUnitType
	EpfcUNIT_MASS                 =1          # from enum EpfcUnitType
	EpfcUNIT_TEMPERATURE          =4          # from enum EpfcUnitType
	EpfcUNIT_TIME                 =3          # from enum EpfcUnitType
	EpfcUnitType_nil              =6          # from enum EpfcUnitType
	EpfcV_JUSTIFY_BOTTOM          =2          # from enum EpfcVerticalJustification
	EpfcV_JUSTIFY_DEFAULT         =3          # from enum EpfcVerticalJustification
	EpfcV_JUSTIFY_MIDDLE          =1          # from enum EpfcVerticalJustification
	EpfcV_JUSTIFY_TOP             =0          # from enum EpfcVerticalJustification
	EpfcVerticalJustification_nil =4          # from enum EpfcVerticalJustification
	EpfcDRAWVIEW_AUXILIARY        =2          # from enum EpfcView2DType
	EpfcDRAWVIEW_COPY_AND_ALIGN   =5          # from enum EpfcView2DType
	EpfcDRAWVIEW_DETAIL           =3          # from enum EpfcView2DType
	EpfcDRAWVIEW_GENERAL          =0          # from enum EpfcView2DType
	EpfcDRAWVIEW_OF_FLAT_TYPE     =6          # from enum EpfcView2DType
	EpfcDRAWVIEW_PROJECTION       =1          # from enum EpfcView2DType
	EpfcDRAWVIEW_REVOLVE          =4          # from enum EpfcView2DType
	EpfcView2DType_nil            =7          # from enum EpfcView2DType
	EpfcWSIMPEX_MSG_CONFLICT      =2          # from enum EpfcWSImportExportMessageType
	EpfcWSIMPEX_MSG_ERROR         =3          # from enum EpfcWSImportExportMessageType
	EpfcWSIMPEX_MSG_INFO          =0          # from enum EpfcWSImportExportMessageType
	EpfcWSIMPEX_MSG_WARNING       =1          # from enum EpfcWSImportExportMessageType
	EpfcWSImportExportMessageType_nil=4          # from enum EpfcWSImportExportMessageType
	EpfcXSEC_OFFSET               =1          # from enum EpfcXSecCutType
	EpfcXSEC_PLANAR               =0          # from enum EpfcXSecCutType
	EpfcXSecCutType_nil           =2          # from enum EpfcXSecCutType
	EpfcXSECTYPE_MODEL            =0          # from enum EpfcXSecCutobjType
	EpfcXSECTYPE_MODELQUILTS      =2          # from enum EpfcXSecCutobjType
	EpfcXSECTYPE_QUILTS           =1          # from enum EpfcXSecCutobjType
	EpfcXSecCutobjType_nil        =3          # from enum EpfcXSecCutobjType
